package eshviewer.data;
// Generated Jan 29, 2018 4:14:35 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CodeValueSet generated by hbm2java
 */
@Entity
@Table(name="CODE_VALUE_SET"
    ,schema="V500"
)
public class CodeValueSet  implements java.io.Serializable {


     private BigDecimal codeSet;
     private String display;
     private String displayKey;
     private String description;
     private String definition;
     private String tableName;
     private String contributor;
     private String ownerModule;
     private BigDecimal cacheInd;
     private BigDecimal extensionInd;
     private BigDecimal addAccessInd;
     private BigDecimal chgAccessInd;
     private BigDecimal delAccessInd;
     private BigDecimal inqAccessInd;
     private BigDecimal domainQualifierInd;
     private BigDecimal domainCodeSet;
     private Date updtDtTm;
     private BigDecimal updtId;
     private BigDecimal updtCnt;
     private BigDecimal updtTask;
     private BigDecimal updtApplctx;
     private BigDecimal codeSetHits;
     private BigDecimal codeValuesCnt;
     private BigDecimal defDupRuleFlag;
     private BigDecimal cdfMeaningDupInd;
     private BigDecimal displayKeyDupInd;
     private BigDecimal activeIndDupInd;
     private BigDecimal displayDupInd;
     private BigDecimal aliasDupInd;
     private BigDecimal definitionDupInd;
     private Date lastUtcTs;
     private Set<CodeValueAlias> codeValueAliases = new HashSet<CodeValueAlias>(0);

    public CodeValueSet() {
    }

	
    public CodeValueSet(BigDecimal codeSet, Date updtDtTm, BigDecimal updtId, BigDecimal updtCnt, BigDecimal updtTask, BigDecimal updtApplctx) {
        this.codeSet = codeSet;
        this.updtDtTm = updtDtTm;
        this.updtId = updtId;
        this.updtCnt = updtCnt;
        this.updtTask = updtTask;
        this.updtApplctx = updtApplctx;
    }
    public CodeValueSet(BigDecimal codeSet, String display, String displayKey, String description, String definition, String tableName, String contributor, String ownerModule, BigDecimal cacheInd, BigDecimal extensionInd, BigDecimal addAccessInd, BigDecimal chgAccessInd, BigDecimal delAccessInd, BigDecimal inqAccessInd, BigDecimal domainQualifierInd, BigDecimal domainCodeSet, Date updtDtTm, BigDecimal updtId, BigDecimal updtCnt, BigDecimal updtTask, BigDecimal updtApplctx, BigDecimal codeSetHits, BigDecimal codeValuesCnt, BigDecimal defDupRuleFlag, BigDecimal cdfMeaningDupInd, BigDecimal displayKeyDupInd, BigDecimal activeIndDupInd, BigDecimal displayDupInd, BigDecimal aliasDupInd, BigDecimal definitionDupInd, Date lastUtcTs, Set<CodeValueAlias> codeValueAliases) {
       this.codeSet = codeSet;
       this.display = display;
       this.displayKey = displayKey;
       this.description = description;
       this.definition = definition;
       this.tableName = tableName;
       this.contributor = contributor;
       this.ownerModule = ownerModule;
       this.cacheInd = cacheInd;
       this.extensionInd = extensionInd;
       this.addAccessInd = addAccessInd;
       this.chgAccessInd = chgAccessInd;
       this.delAccessInd = delAccessInd;
       this.inqAccessInd = inqAccessInd;
       this.domainQualifierInd = domainQualifierInd;
       this.domainCodeSet = domainCodeSet;
       this.updtDtTm = updtDtTm;
       this.updtId = updtId;
       this.updtCnt = updtCnt;
       this.updtTask = updtTask;
       this.updtApplctx = updtApplctx;
       this.codeSetHits = codeSetHits;
       this.codeValuesCnt = codeValuesCnt;
       this.defDupRuleFlag = defDupRuleFlag;
       this.cdfMeaningDupInd = cdfMeaningDupInd;
       this.displayKeyDupInd = displayKeyDupInd;
       this.activeIndDupInd = activeIndDupInd;
       this.displayDupInd = displayDupInd;
       this.aliasDupInd = aliasDupInd;
       this.definitionDupInd = definitionDupInd;
       this.lastUtcTs = lastUtcTs;
       this.codeValueAliases = codeValueAliases;
    }
   
     @Id 

    
    @Column(name="CODE_SET", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getCodeSet() {
        return this.codeSet;
    }
    
    public void setCodeSet(BigDecimal codeSet) {
        this.codeSet = codeSet;
    }

    
    @Column(name="DISPLAY", length=40)
    public String getDisplay() {
        return this.display;
    }
    
    public void setDisplay(String display) {
        this.display = display;
    }

    
    @Column(name="DISPLAY_KEY", length=40)
    public String getDisplayKey() {
        return this.displayKey;
    }
    
    public void setDisplayKey(String displayKey) {
        this.displayKey = displayKey;
    }

    
    @Column(name="DESCRIPTION", length=60)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="DEFINITION", length=500)
    public String getDefinition() {
        return this.definition;
    }
    
    public void setDefinition(String definition) {
        this.definition = definition;
    }

    
    @Column(name="TABLE_NAME", length=32)
    public String getTableName() {
        return this.tableName;
    }
    
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    
    @Column(name="CONTRIBUTOR", length=18)
    public String getContributor() {
        return this.contributor;
    }
    
    public void setContributor(String contributor) {
        this.contributor = contributor;
    }

    
    @Column(name="OWNER_MODULE", length=12)
    public String getOwnerModule() {
        return this.ownerModule;
    }
    
    public void setOwnerModule(String ownerModule) {
        this.ownerModule = ownerModule;
    }

    
    @Column(name="CACHE_IND", precision=22, scale=0)
    public BigDecimal getCacheInd() {
        return this.cacheInd;
    }
    
    public void setCacheInd(BigDecimal cacheInd) {
        this.cacheInd = cacheInd;
    }

    
    @Column(name="EXTENSION_IND", precision=22, scale=0)
    public BigDecimal getExtensionInd() {
        return this.extensionInd;
    }
    
    public void setExtensionInd(BigDecimal extensionInd) {
        this.extensionInd = extensionInd;
    }

    
    @Column(name="ADD_ACCESS_IND", precision=22, scale=0)
    public BigDecimal getAddAccessInd() {
        return this.addAccessInd;
    }
    
    public void setAddAccessInd(BigDecimal addAccessInd) {
        this.addAccessInd = addAccessInd;
    }

    
    @Column(name="CHG_ACCESS_IND", precision=22, scale=0)
    public BigDecimal getChgAccessInd() {
        return this.chgAccessInd;
    }
    
    public void setChgAccessInd(BigDecimal chgAccessInd) {
        this.chgAccessInd = chgAccessInd;
    }

    
    @Column(name="DEL_ACCESS_IND", precision=22, scale=0)
    public BigDecimal getDelAccessInd() {
        return this.delAccessInd;
    }
    
    public void setDelAccessInd(BigDecimal delAccessInd) {
        this.delAccessInd = delAccessInd;
    }

    
    @Column(name="INQ_ACCESS_IND", precision=22, scale=0)
    public BigDecimal getInqAccessInd() {
        return this.inqAccessInd;
    }
    
    public void setInqAccessInd(BigDecimal inqAccessInd) {
        this.inqAccessInd = inqAccessInd;
    }

    
    @Column(name="DOMAIN_QUALIFIER_IND", precision=22, scale=0)
    public BigDecimal getDomainQualifierInd() {
        return this.domainQualifierInd;
    }
    
    public void setDomainQualifierInd(BigDecimal domainQualifierInd) {
        this.domainQualifierInd = domainQualifierInd;
    }

    
    @Column(name="DOMAIN_CODE_SET", precision=22, scale=0)
    public BigDecimal getDomainCodeSet() {
        return this.domainCodeSet;
    }
    
    public void setDomainCodeSet(BigDecimal domainCodeSet) {
        this.domainCodeSet = domainCodeSet;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="UPDT_DT_TM", nullable=false, length=7)
    public Date getUpdtDtTm() {
        return this.updtDtTm;
    }
    
    public void setUpdtDtTm(Date updtDtTm) {
        this.updtDtTm = updtDtTm;
    }

    
    @Column(name="UPDT_ID", nullable=false, precision=22, scale=0)
    public BigDecimal getUpdtId() {
        return this.updtId;
    }
    
    public void setUpdtId(BigDecimal updtId) {
        this.updtId = updtId;
    }

    
    @Column(name="UPDT_CNT", nullable=false, precision=22, scale=0)
    public BigDecimal getUpdtCnt() {
        return this.updtCnt;
    }
    
    public void setUpdtCnt(BigDecimal updtCnt) {
        this.updtCnt = updtCnt;
    }

    
    @Column(name="UPDT_TASK", nullable=false, precision=22, scale=0)
    public BigDecimal getUpdtTask() {
        return this.updtTask;
    }
    
    public void setUpdtTask(BigDecimal updtTask) {
        this.updtTask = updtTask;
    }

    
    @Column(name="UPDT_APPLCTX", nullable=false, precision=22, scale=0)
    public BigDecimal getUpdtApplctx() {
        return this.updtApplctx;
    }
    
    public void setUpdtApplctx(BigDecimal updtApplctx) {
        this.updtApplctx = updtApplctx;
    }

    
    @Column(name="CODE_SET_HITS", precision=22, scale=0)
    public BigDecimal getCodeSetHits() {
        return this.codeSetHits;
    }
    
    public void setCodeSetHits(BigDecimal codeSetHits) {
        this.codeSetHits = codeSetHits;
    }

    
    @Column(name="CODE_VALUES_CNT", precision=22, scale=0)
    public BigDecimal getCodeValuesCnt() {
        return this.codeValuesCnt;
    }
    
    public void setCodeValuesCnt(BigDecimal codeValuesCnt) {
        this.codeValuesCnt = codeValuesCnt;
    }

    
    @Column(name="DEF_DUP_RULE_FLAG", precision=22, scale=0)
    public BigDecimal getDefDupRuleFlag() {
        return this.defDupRuleFlag;
    }
    
    public void setDefDupRuleFlag(BigDecimal defDupRuleFlag) {
        this.defDupRuleFlag = defDupRuleFlag;
    }

    
    @Column(name="CDF_MEANING_DUP_IND", precision=22, scale=0)
    public BigDecimal getCdfMeaningDupInd() {
        return this.cdfMeaningDupInd;
    }
    
    public void setCdfMeaningDupInd(BigDecimal cdfMeaningDupInd) {
        this.cdfMeaningDupInd = cdfMeaningDupInd;
    }

    
    @Column(name="DISPLAY_KEY_DUP_IND", precision=22, scale=0)
    public BigDecimal getDisplayKeyDupInd() {
        return this.displayKeyDupInd;
    }
    
    public void setDisplayKeyDupInd(BigDecimal displayKeyDupInd) {
        this.displayKeyDupInd = displayKeyDupInd;
    }

    
    @Column(name="ACTIVE_IND_DUP_IND", precision=22, scale=0)
    public BigDecimal getActiveIndDupInd() {
        return this.activeIndDupInd;
    }
    
    public void setActiveIndDupInd(BigDecimal activeIndDupInd) {
        this.activeIndDupInd = activeIndDupInd;
    }

    
    @Column(name="DISPLAY_DUP_IND", precision=22, scale=0)
    public BigDecimal getDisplayDupInd() {
        return this.displayDupInd;
    }
    
    public void setDisplayDupInd(BigDecimal displayDupInd) {
        this.displayDupInd = displayDupInd;
    }

    
    @Column(name="ALIAS_DUP_IND", precision=22, scale=0)
    public BigDecimal getAliasDupInd() {
        return this.aliasDupInd;
    }
    
    public void setAliasDupInd(BigDecimal aliasDupInd) {
        this.aliasDupInd = aliasDupInd;
    }

    
    @Column(name="DEFINITION_DUP_IND", precision=22, scale=0)
    public BigDecimal getDefinitionDupInd() {
        return this.definitionDupInd;
    }
    
    public void setDefinitionDupInd(BigDecimal definitionDupInd) {
        this.definitionDupInd = definitionDupInd;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_UTC_TS")
    public Date getLastUtcTs() {
        return this.lastUtcTs;
    }
    
    public void setLastUtcTs(Date lastUtcTs) {
        this.lastUtcTs = lastUtcTs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="codeValueSet")
    public Set<CodeValueAlias> getCodeValueAliases() {
        return this.codeValueAliases;
    }
    
    public void setCodeValueAliases(Set<CodeValueAlias> codeValueAliases) {
        this.codeValueAliases = codeValueAliases;
    }




}


