package eshviewer.data;
// Generated Jan 29, 2018 4:14:35 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

/**
 * CodeValueAliasId generated by hbm2java
 */
@Embeddable
public class CodeValueAliasId  implements java.io.Serializable {


     private BigDecimal codeSet;
     private CodeValue contributorSourceCd;
     private String alias;
     private BigDecimal codeValue;
     private BigDecimal primaryInd;
     private Date updtDtTm;
     private BigDecimal updtId;
     private BigDecimal updtTask;
     private BigDecimal updtCnt;
     private BigDecimal updtApplctx;
     private String aliasTypeMeaning;
     //private Date lastUtcTs;

    public CodeValueAliasId() {
    }

	
   


    @Column(name="CODE_SET", nullable=false, precision=22, scale=0)
    public BigDecimal getCodeSet() {
        return this.codeSet;
    }
    
    public void setCodeSet(BigDecimal codeSet) {
        this.codeSet = codeSet;
    }


    //@Column(name="CONTRIBUTOR_SOURCE_CD", nullable=false, precision=22, scale=0)
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CONTRIBUTOR_SOURCE_CD")
    public CodeValue getContributorSourceCd() {
        return this.contributorSourceCd;
    }
    
    public void setContributorSourceCd(CodeValue contributorSourceCd) {
        this.contributorSourceCd = contributorSourceCd;
    }


    @Column(name="ALIAS", nullable=false)
    public String getAlias() {
        return this.alias;
    }
    
    public void setAlias(String alias) {
        this.alias = alias;
    }


    @Column(name="CODE_VALUE", nullable=false, precision=22, scale=0)
    public BigDecimal getCodeValue() {
        return this.codeValue;
    }
    
    public void setCodeValue(BigDecimal codeValue) {
        this.codeValue = codeValue;
    }


    @Column(name="PRIMARY_IND", precision=22, scale=0)
    public BigDecimal getPrimaryInd() {
        return this.primaryInd;
    }
    
    public void setPrimaryInd(BigDecimal primaryInd) {
        this.primaryInd = primaryInd;
    }


    @Column(name="UPDT_DT_TM", nullable=false, length=7)
    public Date getUpdtDtTm() {
        return this.updtDtTm;
    }
    
    public void setUpdtDtTm(Date updtDtTm) {
        this.updtDtTm = updtDtTm;
    }


    @Column(name="UPDT_ID", nullable=false, precision=22, scale=0)
    public BigDecimal getUpdtId() {
        return this.updtId;
    }
    
    public void setUpdtId(BigDecimal updtId) {
        this.updtId = updtId;
    }


    @Column(name="UPDT_TASK", nullable=false, precision=22, scale=0)
    public BigDecimal getUpdtTask() {
        return this.updtTask;
    }
    
    public void setUpdtTask(BigDecimal updtTask) {
        this.updtTask = updtTask;
    }


    @Column(name="UPDT_CNT", nullable=false, precision=22, scale=0)
    public BigDecimal getUpdtCnt() {
        return this.updtCnt;
    }
    
    public void setUpdtCnt(BigDecimal updtCnt) {
        this.updtCnt = updtCnt;
    }


    @Column(name="UPDT_APPLCTX", nullable=false, precision=22, scale=0)
    public BigDecimal getUpdtApplctx() {
        return this.updtApplctx;
    }
    
    public void setUpdtApplctx(BigDecimal updtApplctx) {
        this.updtApplctx = updtApplctx;
    }


    @Column(name="ALIAS_TYPE_MEANING", length=12)
    public String getAliasTypeMeaning() {
        return this.aliasTypeMeaning;
    }
    
    public void setAliasTypeMeaning(String aliasTypeMeaning) {
        this.aliasTypeMeaning = aliasTypeMeaning;
    }


    //@Column(name="LAST_UTC_TS")
    //public Date getLastUtcTs() {
    //    return this.lastUtcTs;
    //}
    //
    //public void setLastUtcTs(Date lastUtcTs) {
    //    this.lastUtcTs = lastUtcTs;
    //}


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CodeValueAliasId) ) return false;
		 CodeValueAliasId castOther = ( CodeValueAliasId ) other; 
         
		 return ( (this.getCodeSet()==castOther.getCodeSet()) || ( this.getCodeSet()!=null && castOther.getCodeSet()!=null && this.getCodeSet().equals(castOther.getCodeSet()) ) )
 && ( (this.getContributorSourceCd()==castOther.getContributorSourceCd()) || ( this.getContributorSourceCd()!=null && castOther.getContributorSourceCd()!=null && this.getContributorSourceCd().equals(castOther.getContributorSourceCd()) ) )
 && ( (this.getAlias()==castOther.getAlias()) || ( this.getAlias()!=null && castOther.getAlias()!=null && this.getAlias().equals(castOther.getAlias()) ) )
 && ( (this.getCodeValue()==castOther.getCodeValue()) || ( this.getCodeValue()!=null && castOther.getCodeValue()!=null && this.getCodeValue().equals(castOther.getCodeValue()) ) )
 && ( (this.getPrimaryInd()==castOther.getPrimaryInd()) || ( this.getPrimaryInd()!=null && castOther.getPrimaryInd()!=null && this.getPrimaryInd().equals(castOther.getPrimaryInd()) ) )
 && ( (this.getUpdtDtTm()==castOther.getUpdtDtTm()) || ( this.getUpdtDtTm()!=null && castOther.getUpdtDtTm()!=null && this.getUpdtDtTm().equals(castOther.getUpdtDtTm()) ) )
 && ( (this.getUpdtId()==castOther.getUpdtId()) || ( this.getUpdtId()!=null && castOther.getUpdtId()!=null && this.getUpdtId().equals(castOther.getUpdtId()) ) )
 && ( (this.getUpdtTask()==castOther.getUpdtTask()) || ( this.getUpdtTask()!=null && castOther.getUpdtTask()!=null && this.getUpdtTask().equals(castOther.getUpdtTask()) ) )
 && ( (this.getUpdtCnt()==castOther.getUpdtCnt()) || ( this.getUpdtCnt()!=null && castOther.getUpdtCnt()!=null && this.getUpdtCnt().equals(castOther.getUpdtCnt()) ) )
 && ( (this.getUpdtApplctx()==castOther.getUpdtApplctx()) || ( this.getUpdtApplctx()!=null && castOther.getUpdtApplctx()!=null && this.getUpdtApplctx().equals(castOther.getUpdtApplctx()) ) )
 && ( (this.getAliasTypeMeaning()==castOther.getAliasTypeMeaning()) || ( this.getAliasTypeMeaning()!=null && castOther.getAliasTypeMeaning()!=null && this.getAliasTypeMeaning().equals(castOther.getAliasTypeMeaning()) ) )
 /*&& ( (this.getLastUtcTs()==castOther.getLastUtcTs()) || ( this.getLastUtcTs()!=null && castOther.getLastUtcTs()!=null && this.getLastUtcTs().equals(castOther.getLastUtcTs()) ) )*/;
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodeSet() == null ? 0 : this.getCodeSet().hashCode() );
         result = 37 * result + ( getContributorSourceCd() == null ? 0 : this.getContributorSourceCd().hashCode() );
         result = 37 * result + ( getAlias() == null ? 0 : this.getAlias().hashCode() );
         result = 37 * result + ( getCodeValue() == null ? 0 : this.getCodeValue().hashCode() );
         result = 37 * result + ( getPrimaryInd() == null ? 0 : this.getPrimaryInd().hashCode() );
         result = 37 * result + ( getUpdtDtTm() == null ? 0 : this.getUpdtDtTm().hashCode() );
         result = 37 * result + ( getUpdtId() == null ? 0 : this.getUpdtId().hashCode() );
         result = 37 * result + ( getUpdtTask() == null ? 0 : this.getUpdtTask().hashCode() );
         result = 37 * result + ( getUpdtCnt() == null ? 0 : this.getUpdtCnt().hashCode() );
         result = 37 * result + ( getUpdtApplctx() == null ? 0 : this.getUpdtApplctx().hashCode() );
         result = 37 * result + ( getAliasTypeMeaning() == null ? 0 : this.getAliasTypeMeaning().hashCode() );
         //result = 37 * result + ( getLastUtcTs() == null ? 0 : this.getLastUtcTs().hashCode() );
         return result;
   }   


}


