package eshviewer.data;
// Generated Jan 29, 2018 4:14:35 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CodeValueAlias generated by hbm2java
 */
@Entity
@Table(name="CODE_VALUE_ALIAS"
    ,schema="V500"
    , uniqueConstraints = @UniqueConstraint(columnNames={"ALIAS", "CODE_SET", "CONTRIBUTOR_SOURCE_CD", "ALIAS_TYPE_MEANING"}) 
)
public class CodeValueAlias  implements java.io.Serializable {


     private CodeValueAliasId id;
     private CodeValue codeValue;
     private CodeValueSet codeValueSet;

    public CodeValueAlias() {
    }

    public CodeValueAlias(CodeValueAliasId id, CodeValue codeValue, CodeValueSet codeValueSet) {
       this.id = id;
       this.codeValue = codeValue;
       this.codeValueSet = codeValueSet;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="codeSet", column=@Column(name="CODE_SET", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="contributorSourceCd", column=@Column(name="CONTRIBUTOR_SOURCE_CD", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="alias", column=@Column(name="ALIAS", nullable=false) ), 
        @AttributeOverride(name="codeValue", column=@Column(name="CODE_VALUE", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="primaryInd", column=@Column(name="PRIMARY_IND", precision=22, scale=0) ), 
        @AttributeOverride(name="updtDtTm", column=@Column(name="UPDT_DT_TM", nullable=false, length=7) ), 
        @AttributeOverride(name="updtId", column=@Column(name="UPDT_ID", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="updtTask", column=@Column(name="UPDT_TASK", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="updtCnt", column=@Column(name="UPDT_CNT", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="updtApplctx", column=@Column(name="UPDT_APPLCTX", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="aliasTypeMeaning", column=@Column(name="ALIAS_TYPE_MEANING", length=12) ), 
        @AttributeOverride(name="lastUtcTs", column=@Column(name="LAST_UTC_TS") ) } )
    public CodeValueAliasId getId() {
        return this.id;
    }
    
    public void setId(CodeValueAliasId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CODE_VALUE", nullable=false, insertable=false, updatable=false)
    public CodeValue getCodeValue() {
        return this.codeValue;
    }
    
    public void setCodeValue(CodeValue codeValue) {
        this.codeValue = codeValue;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CODE_SET", nullable=false, insertable=false, updatable=false)
    public CodeValueSet getCodeValueSet() {
        return this.codeValueSet;
    }
    
    public void setCodeValueSet(CodeValueSet codeValueSet) {
        this.codeValueSet = codeValueSet;
    }




}


