package eshviewer.data;
// Generated Dec 11, 2017 9:52:44 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Transient;

/**
 * CodeValueEventRId generated by hbm2java
 */
@Embeddable
public class CodeValueEventRId  implements java.io.Serializable {


     private double eventCd;
     private double parentCd;
     private BigDecimal flex1Cd;
     private BigDecimal flex2Cd;
     private BigDecimal flex3Cd;
     private BigDecimal flex4Cd;
     private Date updtDtTm;
     private BigDecimal flex5Cd;
     private double updtId;
     private BigDecimal updtTask;
     private BigDecimal updtCnt;
     private BigDecimal updtApplctx;
     private Date lastUtcTs;

    public CodeValueEventRId() {
    }

	
    public CodeValueEventRId(double eventCd, double parentCd, BigDecimal flex1Cd, BigDecimal flex2Cd, BigDecimal flex3Cd, BigDecimal flex4Cd, Date updtDtTm, BigDecimal flex5Cd, double updtId, BigDecimal updtTask, BigDecimal updtCnt, BigDecimal updtApplctx) {
        this.eventCd = eventCd;
        this.parentCd = parentCd;
        this.flex1Cd = flex1Cd;
        this.flex2Cd = flex2Cd;
        this.flex3Cd = flex3Cd;
        this.flex4Cd = flex4Cd;
        this.updtDtTm = updtDtTm;
        this.flex5Cd = flex5Cd;
        this.updtId = updtId;
        this.updtTask = updtTask;
        this.updtCnt = updtCnt;
        this.updtApplctx = updtApplctx;
    }
    public CodeValueEventRId(double eventCd, double parentCd, BigDecimal flex1Cd, BigDecimal flex2Cd, BigDecimal flex3Cd, BigDecimal flex4Cd, Date updtDtTm, BigDecimal flex5Cd, double updtId, BigDecimal updtTask, BigDecimal updtCnt, BigDecimal updtApplctx, Date lastUtcTs) {
       this.eventCd = eventCd;
       this.parentCd = parentCd;
       this.flex1Cd = flex1Cd;
       this.flex2Cd = flex2Cd;
       this.flex3Cd = flex3Cd;
       this.flex4Cd = flex4Cd;
       this.updtDtTm = updtDtTm;
       this.flex5Cd = flex5Cd;
       this.updtId = updtId;
       this.updtTask = updtTask;
       this.updtCnt = updtCnt;
       this.updtApplctx = updtApplctx;
       this.lastUtcTs = lastUtcTs;
    }
   


    @Column(name="EVENT_CD", nullable=false, precision=126, scale=0)
    public double getEventCd() {
        return this.eventCd;
    }
    
    public void setEventCd(double eventCd) {
        this.eventCd = eventCd;
    }


    @Column(name="PARENT_CD", nullable=false, precision=126, scale=0)
    public double getParentCd() {
        return this.parentCd;
    }
    
    public void setParentCd(double parentCd) {
        this.parentCd = parentCd;
    }


    @Column(name="FLEX1_CD", nullable=false, precision=22, scale=0)
    public BigDecimal getFlex1Cd() {
        return this.flex1Cd;
    }
    
    public void setFlex1Cd(BigDecimal flex1Cd) {
        this.flex1Cd = flex1Cd;
    }


    @Column(name="FLEX2_CD", nullable=false, precision=22, scale=0)
    public BigDecimal getFlex2Cd() {
        return this.flex2Cd;
    }
    
    public void setFlex2Cd(BigDecimal flex2Cd) {
        this.flex2Cd = flex2Cd;
    }


    @Column(name="FLEX3_CD", nullable=false, precision=22, scale=0)
    public BigDecimal getFlex3Cd() {
        return this.flex3Cd;
    }
    
    public void setFlex3Cd(BigDecimal flex3Cd) {
        this.flex3Cd = flex3Cd;
    }


    @Column(name="FLEX4_CD", nullable=false, precision=22, scale=0)
    public BigDecimal getFlex4Cd() {
        return this.flex4Cd;
    }
    
    public void setFlex4Cd(BigDecimal flex4Cd) {
        this.flex4Cd = flex4Cd;
    }


    @Column(name="UPDT_DT_TM", nullable=false, length=7)
    public Date getUpdtDtTm() {
        return this.updtDtTm;
    }
    
    public void setUpdtDtTm(Date updtDtTm) {
        this.updtDtTm = updtDtTm;
    }


    @Column(name="FLEX5_CD", nullable=false, precision=22, scale=0)
    public BigDecimal getFlex5Cd() {
        return this.flex5Cd;
    }
    
    public void setFlex5Cd(BigDecimal flex5Cd) {
        this.flex5Cd = flex5Cd;
    }


    @Column(name="UPDT_ID", nullable=false, precision=126, scale=0)
    public double getUpdtId() {
        return this.updtId;
    }
    
    public void setUpdtId(double updtId) {
        this.updtId = updtId;
    }


    @Column(name="UPDT_TASK", nullable=false, precision=22, scale=0)
    public BigDecimal getUpdtTask() {
        return this.updtTask;
    }
    
    public void setUpdtTask(BigDecimal updtTask) {
        this.updtTask = updtTask;
    }


    @Column(name="UPDT_CNT", nullable=false, precision=22, scale=0)
    public BigDecimal getUpdtCnt() {
        return this.updtCnt;
    }
    
    public void setUpdtCnt(BigDecimal updtCnt) {
        this.updtCnt = updtCnt;
    }


    @Column(name="UPDT_APPLCTX", nullable=false, precision=22, scale=0)
    public BigDecimal getUpdtApplctx() {
        return this.updtApplctx;
    }
    
    public void setUpdtApplctx(BigDecimal updtApplctx) {
        this.updtApplctx = updtApplctx;
    }


    /*@Column(name="LAST_UTC_TS")*/
    @Transient
    public Date getLastUtcTs() {
        return this.lastUtcTs;
    }
    
    public void setLastUtcTs(Date lastUtcTs) {
        this.lastUtcTs = lastUtcTs;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CodeValueEventRId) ) return false;
		 CodeValueEventRId castOther = ( CodeValueEventRId ) other; 
         
		 return (this.getEventCd()==castOther.getEventCd())
 && (this.getParentCd()==castOther.getParentCd())
 && ( (this.getFlex1Cd()==castOther.getFlex1Cd()) || ( this.getFlex1Cd()!=null && castOther.getFlex1Cd()!=null && this.getFlex1Cd().equals(castOther.getFlex1Cd()) ) )
 && ( (this.getFlex2Cd()==castOther.getFlex2Cd()) || ( this.getFlex2Cd()!=null && castOther.getFlex2Cd()!=null && this.getFlex2Cd().equals(castOther.getFlex2Cd()) ) )
 && ( (this.getFlex3Cd()==castOther.getFlex3Cd()) || ( this.getFlex3Cd()!=null && castOther.getFlex3Cd()!=null && this.getFlex3Cd().equals(castOther.getFlex3Cd()) ) )
 && ( (this.getFlex4Cd()==castOther.getFlex4Cd()) || ( this.getFlex4Cd()!=null && castOther.getFlex4Cd()!=null && this.getFlex4Cd().equals(castOther.getFlex4Cd()) ) )
 && ( (this.getUpdtDtTm()==castOther.getUpdtDtTm()) || ( this.getUpdtDtTm()!=null && castOther.getUpdtDtTm()!=null && this.getUpdtDtTm().equals(castOther.getUpdtDtTm()) ) )
 && ( (this.getFlex5Cd()==castOther.getFlex5Cd()) || ( this.getFlex5Cd()!=null && castOther.getFlex5Cd()!=null && this.getFlex5Cd().equals(castOther.getFlex5Cd()) ) )
 && (this.getUpdtId()==castOther.getUpdtId())
 && ( (this.getUpdtTask()==castOther.getUpdtTask()) || ( this.getUpdtTask()!=null && castOther.getUpdtTask()!=null && this.getUpdtTask().equals(castOther.getUpdtTask()) ) )
 && ( (this.getUpdtCnt()==castOther.getUpdtCnt()) || ( this.getUpdtCnt()!=null && castOther.getUpdtCnt()!=null && this.getUpdtCnt().equals(castOther.getUpdtCnt()) ) )
 && ( (this.getUpdtApplctx()==castOther.getUpdtApplctx()) || ( this.getUpdtApplctx()!=null && castOther.getUpdtApplctx()!=null && this.getUpdtApplctx().equals(castOther.getUpdtApplctx()) ) )
 && ( (this.getLastUtcTs()==castOther.getLastUtcTs()) || ( this.getLastUtcTs()!=null && castOther.getLastUtcTs()!=null && this.getLastUtcTs().equals(castOther.getLastUtcTs()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getEventCd();
         result = 37 * result + (int) this.getParentCd();
         result = 37 * result + ( getFlex1Cd() == null ? 0 : this.getFlex1Cd().hashCode() );
         result = 37 * result + ( getFlex2Cd() == null ? 0 : this.getFlex2Cd().hashCode() );
         result = 37 * result + ( getFlex3Cd() == null ? 0 : this.getFlex3Cd().hashCode() );
         result = 37 * result + ( getFlex4Cd() == null ? 0 : this.getFlex4Cd().hashCode() );
         result = 37 * result + ( getUpdtDtTm() == null ? 0 : this.getUpdtDtTm().hashCode() );
         result = 37 * result + ( getFlex5Cd() == null ? 0 : this.getFlex5Cd().hashCode() );
         result = 37 * result + (int) this.getUpdtId();
         result = 37 * result + ( getUpdtTask() == null ? 0 : this.getUpdtTask().hashCode() );
         result = 37 * result + ( getUpdtCnt() == null ? 0 : this.getUpdtCnt().hashCode() );
         result = 37 * result + ( getUpdtApplctx() == null ? 0 : this.getUpdtApplctx().hashCode() );
         result = 37 * result + ( getLastUtcTs() == null ? 0 : this.getLastUtcTs().hashCode() );
         return result;
   }   


}


