package eshviewer.data;
// Generated Jan 29, 2018 2:30:46 PM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonBackReference;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * OrderCatalogSynonym generated by hbm2java
 */
@Entity
@Table(name="ORDER_CATALOG_SYNONYM"
    ,schema="V500"
    , uniqueConstraints = @UniqueConstraint(columnNames={"CATALOG_CD", "MNEMONIC_TYPE_CD", "MNEMONIC_KEY_CAP", "ITEM_ID"}) 
)
public class OrderCatalogSynonym  implements java.io.Serializable {


     private BigDecimal synonymId;
     private OrderCatalog orderCatalog;
     private CodeValue catalogTypeCd;
     private String mnemonic;
     private String mnemonicKeyCap;
     private CodeValue mnemonicTypeCd;
     private BigDecimal oeFormatId;
     private BigDecimal orderSentenceId;
     private BigDecimal activeInd;
     private CodeValue activityTypeCd;
     private BigDecimal updtApplctx;
     private BigDecimal updtCnt;
     private Date updtDtTm;
     private BigDecimal updtId;
     private BigDecimal updtTask;
     private CodeValue activitySubtypeCd;
     private BigDecimal orderableTypeFlag;
     private CodeValue activeStatusCd;
     private Date activeStatusDtTm;
     private BigDecimal activeStatusPrsnlId;
     private BigDecimal refTextMask;
     private BigDecimal csIndexCd;
     private BigDecimal multipleOrdSentInd;
     private BigDecimal hideFlag;
     private BigDecimal rxMask;
     private BigDecimal dcpClinCatCd;
     private BigDecimal filteredOdInd;
     private BigDecimal itemId;
     private String cki;
     private String mnemonicKeyCapNls;
     private String virtualView;
     private String healthPlanView;
     private String conceptCki;
     private Double concentrationStrength;
     private BigDecimal concentrationStrengthUnitCd;
     private Double concentrationVolume;
     private BigDecimal concentrationVolumeUnitCd;
     private BigDecimal templateMnemonicFlag;
     private BigDecimal ingredientRateConversionInd;
     private BigDecimal witnessFlag;
     private BigDecimal highAlertLongTextId;
     private BigDecimal highAlertInd;
     private BigDecimal highAlertRequiredNtfyInd;
     private BigDecimal roundingRuleCd;
     private BigDecimal medIntervalWarnFlag;
     private BigDecimal lastAdminDispBasisFlag;
     private BigDecimal displayAdditivesFirstInd;
     private String mnemonicKeyCapANls;
     private BigDecimal intermittentInd;
     private BigDecimal ignoreHideConvertInd;
     private BigDecimal lockTargetDoseInd;
     private BigDecimal autoprogSynInd;
     private Double maxFinalDose;
     private BigDecimal preferredDoseFlag;
     private BigDecimal maxDoseCalcBsaValue;
     private BigDecimal maxFinalDoseUnitCd;
     private Date lastUtcTs;

    public OrderCatalogSynonym() {
    }

	
   
     @Id 

    
    @Column(name="SYNONYM_ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getSynonymId() {
        return this.synonymId;
    }
    
    public void setSynonymId(BigDecimal synonymId) {
        this.synonymId = synonymId;
    }

@JsonBackReference
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CATALOG_CD", nullable=false)
    public OrderCatalog getOrderCatalog() {
        return this.orderCatalog;
    }
    
    public void setOrderCatalog(OrderCatalog orderCatalog) {
        this.orderCatalog = orderCatalog;
    }

    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CATALOG_TYPE_CD")
    public CodeValue getCatalogTypeCd() {
        return this.catalogTypeCd;
    }
    
    public void setCatalogTypeCd(CodeValue catalogTypeCd) {
        this.catalogTypeCd = catalogTypeCd;
    }

    
    @Column(name="MNEMONIC", length=100)
    public String getMnemonic() {
        return this.mnemonic;
    }
    
    public void setMnemonic(String mnemonic) {
        this.mnemonic = mnemonic;
    }

    
    @Column(name="MNEMONIC_KEY_CAP", length=100)
    public String getMnemonicKeyCap() {
        return this.mnemonicKeyCap;
    }
    
    public void setMnemonicKeyCap(String mnemonicKeyCap) {
        this.mnemonicKeyCap = mnemonicKeyCap;
    }

    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MNEMONIC_TYPE_CD")
    public CodeValue getMnemonicTypeCd() {
        return this.mnemonicTypeCd;
    }
    
    public void setMnemonicTypeCd(CodeValue mnemonicTypeCd) {
        this.mnemonicTypeCd = mnemonicTypeCd;
    }

    
    @Column(name="OE_FORMAT_ID", nullable=false, precision=22, scale=0)
    public BigDecimal getOeFormatId() {
        return this.oeFormatId;
    }
    
    public void setOeFormatId(BigDecimal oeFormatId) {
        this.oeFormatId = oeFormatId;
    }

    
    @Column(name="ORDER_SENTENCE_ID", nullable=false, precision=22, scale=0)
    public BigDecimal getOrderSentenceId() {
        return this.orderSentenceId;
    }
    
    public void setOrderSentenceId(BigDecimal orderSentenceId) {
        this.orderSentenceId = orderSentenceId;
    }

    
    @Column(name="ACTIVE_IND", precision=22, scale=0)
    public BigDecimal getActiveInd() {
        return this.activeInd;
    }
    
    public void setActiveInd(BigDecimal activeInd) {
        this.activeInd = activeInd;
    }

    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ACTIVITY_TYPE_CD")
    public CodeValue getActivityTypeCd() {
        return this.activityTypeCd;
    }
    
    public void setActivityTypeCd(CodeValue activityTypeCd) {
        this.activityTypeCd = activityTypeCd;
    }

    
    @Column(name="UPDT_APPLCTX", nullable=false, precision=22, scale=0)
    public BigDecimal getUpdtApplctx() {
        return this.updtApplctx;
    }
    
    public void setUpdtApplctx(BigDecimal updtApplctx) {
        this.updtApplctx = updtApplctx;
    }

    
    @Column(name="UPDT_CNT", nullable=false, precision=22, scale=0)
    public BigDecimal getUpdtCnt() {
        return this.updtCnt;
    }
    
    public void setUpdtCnt(BigDecimal updtCnt) {
        this.updtCnt = updtCnt;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="UPDT_DT_TM", nullable=false, length=7)
    public Date getUpdtDtTm() {
        return this.updtDtTm;
    }
    
    public void setUpdtDtTm(Date updtDtTm) {
        this.updtDtTm = updtDtTm;
    }

    
    @Column(name="UPDT_ID", nullable=false, precision=22, scale=0)
    public BigDecimal getUpdtId() {
        return this.updtId;
    }
    
    public void setUpdtId(BigDecimal updtId) {
        this.updtId = updtId;
    }

    
    @Column(name="UPDT_TASK", nullable=false, precision=22, scale=0)
    public BigDecimal getUpdtTask() {
        return this.updtTask;
    }
    
    public void setUpdtTask(BigDecimal updtTask) {
        this.updtTask = updtTask;
    }

    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ACTIVITY_SUBTYPE_CD")
    public CodeValue getActivitySubtypeCd() {
        return this.activitySubtypeCd;
    }
    
    public void setActivitySubtypeCd(CodeValue activitySubtypeCd) {
        this.activitySubtypeCd = activitySubtypeCd;
    }

    
    @Column(name="ORDERABLE_TYPE_FLAG", precision=22, scale=0)
    public BigDecimal getOrderableTypeFlag() {
        return this.orderableTypeFlag;
    }
    
    public void setOrderableTypeFlag(BigDecimal orderableTypeFlag) {
        this.orderableTypeFlag = orderableTypeFlag;
    }

    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ACTIVE_STATUS_CD")
    public CodeValue getActiveStatusCd() {
        return this.activeStatusCd;
    }
    
    public void setActiveStatusCd(CodeValue activeStatusCd) {
        this.activeStatusCd = activeStatusCd;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ACTIVE_STATUS_DT_TM", length=7)
    public Date getActiveStatusDtTm() {
        return this.activeStatusDtTm;
    }
    
    public void setActiveStatusDtTm(Date activeStatusDtTm) {
        this.activeStatusDtTm = activeStatusDtTm;
    }

    
    @Column(name="ACTIVE_STATUS_PRSNL_ID", nullable=false, precision=22, scale=0)
    public BigDecimal getActiveStatusPrsnlId() {
        return this.activeStatusPrsnlId;
    }
    
    public void setActiveStatusPrsnlId(BigDecimal activeStatusPrsnlId) {
        this.activeStatusPrsnlId = activeStatusPrsnlId;
    }

    
    @Column(name="REF_TEXT_MASK", precision=22, scale=0)
    public BigDecimal getRefTextMask() {
        return this.refTextMask;
    }
    
    public void setRefTextMask(BigDecimal refTextMask) {
        this.refTextMask = refTextMask;
    }

    
    @Column(name="CS_INDEX_CD", nullable=false, precision=22, scale=0)
    public BigDecimal getCsIndexCd() {
        return this.csIndexCd;
    }
    
    public void setCsIndexCd(BigDecimal csIndexCd) {
        this.csIndexCd = csIndexCd;
    }

    
    @Column(name="MULTIPLE_ORD_SENT_IND", precision=22, scale=0)
    public BigDecimal getMultipleOrdSentInd() {
        return this.multipleOrdSentInd;
    }
    
    public void setMultipleOrdSentInd(BigDecimal multipleOrdSentInd) {
        this.multipleOrdSentInd = multipleOrdSentInd;
    }

    
    @Column(name="HIDE_FLAG", precision=22, scale=0)
    public BigDecimal getHideFlag() {
        return this.hideFlag;
    }
    
    public void setHideFlag(BigDecimal hideFlag) {
        this.hideFlag = hideFlag;
    }

    
    @Column(name="RX_MASK", precision=22, scale=0)
    public BigDecimal getRxMask() {
        return this.rxMask;
    }
    
    public void setRxMask(BigDecimal rxMask) {
        this.rxMask = rxMask;
    }

    
    @Column(name="DCP_CLIN_CAT_CD", nullable=false, precision=22, scale=0)
    public BigDecimal getDcpClinCatCd() {
        return this.dcpClinCatCd;
    }
    
    public void setDcpClinCatCd(BigDecimal dcpClinCatCd) {
        this.dcpClinCatCd = dcpClinCatCd;
    }

    
    @Column(name="FILTERED_OD_IND", precision=22, scale=0)
    public BigDecimal getFilteredOdInd() {
        return this.filteredOdInd;
    }
    
    public void setFilteredOdInd(BigDecimal filteredOdInd) {
        this.filteredOdInd = filteredOdInd;
    }

    
    @Column(name="ITEM_ID", nullable=false, precision=22, scale=0)
    public BigDecimal getItemId() {
        return this.itemId;
    }
    
    public void setItemId(BigDecimal itemId) {
        this.itemId = itemId;
    }

    
    @Column(name="CKI")
    public String getCki() {
        return this.cki;
    }
    
    public void setCki(String cki) {
        this.cki = cki;
    }

    
    @Column(name="MNEMONIC_KEY_CAP_NLS", length=405)
    public String getMnemonicKeyCapNls() {
        return this.mnemonicKeyCapNls;
    }
    
    public void setMnemonicKeyCapNls(String mnemonicKeyCapNls) {
        this.mnemonicKeyCapNls = mnemonicKeyCapNls;
    }

    
    @Column(name="VIRTUAL_VIEW", length=100)
    public String getVirtualView() {
        return this.virtualView;
    }
    
    public void setVirtualView(String virtualView) {
        this.virtualView = virtualView;
    }

    
    @Column(name="HEALTH_PLAN_VIEW")
    public String getHealthPlanView() {
        return this.healthPlanView;
    }
    
    public void setHealthPlanView(String healthPlanView) {
        this.healthPlanView = healthPlanView;
    }

    
    @Column(name="CONCEPT_CKI")
    public String getConceptCki() {
        return this.conceptCki;
    }
    
    public void setConceptCki(String conceptCki) {
        this.conceptCki = conceptCki;
    }

    
    @Column(name="CONCENTRATION_STRENGTH", precision=126, scale=0)
    public Double getConcentrationStrength() {
        return this.concentrationStrength;
    }
    
    public void setConcentrationStrength(Double concentrationStrength) {
        this.concentrationStrength = concentrationStrength;
    }

    
    @Column(name="CONCENTRATION_STRENGTH_UNIT_CD", nullable=false, precision=22, scale=0)
    public BigDecimal getConcentrationStrengthUnitCd() {
        return this.concentrationStrengthUnitCd;
    }
    
    public void setConcentrationStrengthUnitCd(BigDecimal concentrationStrengthUnitCd) {
        this.concentrationStrengthUnitCd = concentrationStrengthUnitCd;
    }

    
    @Column(name="CONCENTRATION_VOLUME", precision=126, scale=0)
    public Double getConcentrationVolume() {
        return this.concentrationVolume;
    }
    
    public void setConcentrationVolume(Double concentrationVolume) {
        this.concentrationVolume = concentrationVolume;
    }

    
    @Column(name="CONCENTRATION_VOLUME_UNIT_CD", nullable=false, precision=22, scale=0)
    public BigDecimal getConcentrationVolumeUnitCd() {
        return this.concentrationVolumeUnitCd;
    }
    
    public void setConcentrationVolumeUnitCd(BigDecimal concentrationVolumeUnitCd) {
        this.concentrationVolumeUnitCd = concentrationVolumeUnitCd;
    }

    
    @Column(name="TEMPLATE_MNEMONIC_FLAG", nullable=false, precision=22, scale=0)
    public BigDecimal getTemplateMnemonicFlag() {
        return this.templateMnemonicFlag;
    }
    
    public void setTemplateMnemonicFlag(BigDecimal templateMnemonicFlag) {
        this.templateMnemonicFlag = templateMnemonicFlag;
    }

    
    @Column(name="INGREDIENT_RATE_CONVERSION_IND", nullable=false, precision=22, scale=0)
    public BigDecimal getIngredientRateConversionInd() {
        return this.ingredientRateConversionInd;
    }
    
    public void setIngredientRateConversionInd(BigDecimal ingredientRateConversionInd) {
        this.ingredientRateConversionInd = ingredientRateConversionInd;
    }

    
    @Column(name="WITNESS_FLAG", nullable=false, precision=22, scale=0)
    public BigDecimal getWitnessFlag() {
        return this.witnessFlag;
    }
    
    public void setWitnessFlag(BigDecimal witnessFlag) {
        this.witnessFlag = witnessFlag;
    }

    
    @Column(name="HIGH_ALERT_LONG_TEXT_ID", precision=22, scale=0)
    public BigDecimal getHighAlertLongTextId() {
        return this.highAlertLongTextId;
    }
    
    public void setHighAlertLongTextId(BigDecimal highAlertLongTextId) {
        this.highAlertLongTextId = highAlertLongTextId;
    }

    
    @Column(name="HIGH_ALERT_IND", precision=22, scale=0)
    public BigDecimal getHighAlertInd() {
        return this.highAlertInd;
    }
    
    public void setHighAlertInd(BigDecimal highAlertInd) {
        this.highAlertInd = highAlertInd;
    }

    
    @Column(name="HIGH_ALERT_REQUIRED_NTFY_IND", precision=22, scale=0)
    public BigDecimal getHighAlertRequiredNtfyInd() {
        return this.highAlertRequiredNtfyInd;
    }
    
    public void setHighAlertRequiredNtfyInd(BigDecimal highAlertRequiredNtfyInd) {
        this.highAlertRequiredNtfyInd = highAlertRequiredNtfyInd;
    }

    
    @Column(name="ROUNDING_RULE_CD", precision=22, scale=0)
    public BigDecimal getRoundingRuleCd() {
        return this.roundingRuleCd;
    }
    
    public void setRoundingRuleCd(BigDecimal roundingRuleCd) {
        this.roundingRuleCd = roundingRuleCd;
    }

    
    @Column(name="MED_INTERVAL_WARN_FLAG", precision=22, scale=0)
    public BigDecimal getMedIntervalWarnFlag() {
        return this.medIntervalWarnFlag;
    }
    
    public void setMedIntervalWarnFlag(BigDecimal medIntervalWarnFlag) {
        this.medIntervalWarnFlag = medIntervalWarnFlag;
    }

    
    @Column(name="LAST_ADMIN_DISP_BASIS_FLAG", precision=22, scale=0)
    public BigDecimal getLastAdminDispBasisFlag() {
        return this.lastAdminDispBasisFlag;
    }
    
    public void setLastAdminDispBasisFlag(BigDecimal lastAdminDispBasisFlag) {
        this.lastAdminDispBasisFlag = lastAdminDispBasisFlag;
    }

    
    @Column(name="DISPLAY_ADDITIVES_FIRST_IND", precision=22, scale=0)
    public BigDecimal getDisplayAdditivesFirstInd() {
        return this.displayAdditivesFirstInd;
    }
    
    public void setDisplayAdditivesFirstInd(BigDecimal displayAdditivesFirstInd) {
        this.displayAdditivesFirstInd = displayAdditivesFirstInd;
    }

    
    @Column(name="MNEMONIC_KEY_CAP_A_NLS", length=400)
    public String getMnemonicKeyCapANls() {
        return this.mnemonicKeyCapANls;
    }
    
    public void setMnemonicKeyCapANls(String mnemonicKeyCapANls) {
        this.mnemonicKeyCapANls = mnemonicKeyCapANls;
    }

    
    @Column(name="INTERMITTENT_IND", precision=22, scale=0)
    public BigDecimal getIntermittentInd() {
        return this.intermittentInd;
    }
    
    public void setIntermittentInd(BigDecimal intermittentInd) {
        this.intermittentInd = intermittentInd;
    }

    
    @Column(name="IGNORE_HIDE_CONVERT_IND", precision=22, scale=0)
    public BigDecimal getIgnoreHideConvertInd() {
        return this.ignoreHideConvertInd;
    }
    
    public void setIgnoreHideConvertInd(BigDecimal ignoreHideConvertInd) {
        this.ignoreHideConvertInd = ignoreHideConvertInd;
    }

    
    @Column(name="LOCK_TARGET_DOSE_IND", precision=22, scale=0)
    public BigDecimal getLockTargetDoseInd() {
        return this.lockTargetDoseInd;
    }
    
    public void setLockTargetDoseInd(BigDecimal lockTargetDoseInd) {
        this.lockTargetDoseInd = lockTargetDoseInd;
    }

    
    @Column(name="AUTOPROG_SYN_IND", precision=22, scale=0)
    public BigDecimal getAutoprogSynInd() {
        return this.autoprogSynInd;
    }
    
    public void setAutoprogSynInd(BigDecimal autoprogSynInd) {
        this.autoprogSynInd = autoprogSynInd;
    }

    
    @Column(name="MAX_FINAL_DOSE", precision=126, scale=0)
    public Double getMaxFinalDose() {
        return this.maxFinalDose;
    }
    
    public void setMaxFinalDose(Double maxFinalDose) {
        this.maxFinalDose = maxFinalDose;
    }

    
    @Column(name="PREFERRED_DOSE_FLAG", precision=22, scale=0)
    public BigDecimal getPreferredDoseFlag() {
        return this.preferredDoseFlag;
    }
    
    public void setPreferredDoseFlag(BigDecimal preferredDoseFlag) {
        this.preferredDoseFlag = preferredDoseFlag;
    }

    
    @Column(name="MAX_DOSE_CALC_BSA_VALUE", precision=22, scale=0)
    public BigDecimal getMaxDoseCalcBsaValue() {
        return this.maxDoseCalcBsaValue;
    }
    
    public void setMaxDoseCalcBsaValue(BigDecimal maxDoseCalcBsaValue) {
        this.maxDoseCalcBsaValue = maxDoseCalcBsaValue;
    }

    
    @Column(name="MAX_FINAL_DOSE_UNIT_CD", precision=22, scale=0)
    public BigDecimal getMaxFinalDoseUnitCd() {
        return this.maxFinalDoseUnitCd;
    }
    
    public void setMaxFinalDoseUnitCd(BigDecimal maxFinalDoseUnitCd) {
        this.maxFinalDoseUnitCd = maxFinalDoseUnitCd;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_UTC_TS")
    public Date getLastUtcTs() {
        return this.lastUtcTs;
    }
    
    public void setLastUtcTs(Date lastUtcTs) {
        this.lastUtcTs = lastUtcTs;
    }




}


