package eshviewer.data;
// Generated Dec 11, 2017 9:52:44 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProfileTaskRId generated by hbm2java
 */
@Embeddable
public class ProfileTaskRId  implements java.io.Serializable {


     private BigDecimal catalogCd;
     private BigDecimal taskAssayCd;

    public ProfileTaskRId() {
    }

    public ProfileTaskRId(BigDecimal catalogCd, BigDecimal taskAssayCd) {
       this.catalogCd = catalogCd;
       this.taskAssayCd = taskAssayCd;
    }
   


    @Column(name="CATALOG_CD", nullable=false, precision=22, scale=0)
    public BigDecimal getCatalogCd() {
        return this.catalogCd;
    }
    
    public void setCatalogCd(BigDecimal catalogCd) {
        this.catalogCd = catalogCd;
    }


    @Column(name="TASK_ASSAY_CD", nullable=false, precision=22, scale=0)
    public BigDecimal getTaskAssayCd() {
        return this.taskAssayCd;
    }
    
    public void setTaskAssayCd(BigDecimal taskAssayCd) {
        this.taskAssayCd = taskAssayCd;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProfileTaskRId) ) return false;
		 ProfileTaskRId castOther = ( ProfileTaskRId ) other; 
         
		 return ( (this.getCatalogCd()==castOther.getCatalogCd()) || ( this.getCatalogCd()!=null && castOther.getCatalogCd()!=null && this.getCatalogCd().equals(castOther.getCatalogCd()) ) )
 && ( (this.getTaskAssayCd()==castOther.getTaskAssayCd()) || ( this.getTaskAssayCd()!=null && castOther.getTaskAssayCd()!=null && this.getTaskAssayCd().equals(castOther.getTaskAssayCd()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCatalogCd() == null ? 0 : this.getCatalogCd().hashCode() );
         result = 37 * result + ( getTaskAssayCd() == null ? 0 : this.getTaskAssayCd().hashCode() );
         return result;
   }   


}


