package eshviewer.data;
// Generated Dec 11, 2017 9:52:44 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProfileTaskR generated by hbm2java
 */
@Entity
@Table(name="PROFILE_TASK_R"
    ,schema="V500"
)
public class ProfileTaskR  implements java.io.Serializable {


     private ProfileTaskRId id;
     private DiscreteTaskAssay discreteTaskAssay;
     private BigDecimal versionNbr;
     private BigDecimal groupCd;
     private BigDecimal itemTypeFlag;
     private BigDecimal pendingInd;
     private BigDecimal repeatInd;
     private BigDecimal sequence;
     private BigDecimal dupChkMin;
     private BigDecimal dupChkActionCd;
     private Date updtDtTm;
     private BigDecimal updtId;
     private BigDecimal updtTask;
     private BigDecimal updtCnt;
     private BigDecimal updtApplctx;
     private BigDecimal activeInd;
     private BigDecimal postPromptInd;
     private BigDecimal promptResourceCd;
     private BigDecimal activeStatusCd;
     private Date activeStatusDtTm;
     private BigDecimal activeStatusPrsnlId;
     private Date begEffectiveDtTm;
     private Date endEffectiveDtTm;
     private BigDecimal referenceTaskId;
     private BigDecimal promptLongTextId;
     private BigDecimal restrictDisplayInd;
     private Date lastUtcTs;

    public ProfileTaskR() {
    }

	
    public ProfileTaskR(ProfileTaskRId id, DiscreteTaskAssay discreteTaskAssay, BigDecimal groupCd, BigDecimal dupChkActionCd, Date updtDtTm, BigDecimal updtId, BigDecimal updtTask, BigDecimal updtCnt, BigDecimal updtApplctx, BigDecimal promptResourceCd, BigDecimal activeStatusCd, BigDecimal activeStatusPrsnlId, Date begEffectiveDtTm, Date endEffectiveDtTm, BigDecimal referenceTaskId, BigDecimal promptLongTextId) {
        this.id = id;
        this.discreteTaskAssay = discreteTaskAssay;
        this.groupCd = groupCd;
        this.dupChkActionCd = dupChkActionCd;
        this.updtDtTm = updtDtTm;
        this.updtId = updtId;
        this.updtTask = updtTask;
        this.updtCnt = updtCnt;
        this.updtApplctx = updtApplctx;
        this.promptResourceCd = promptResourceCd;
        this.activeStatusCd = activeStatusCd;
        this.activeStatusPrsnlId = activeStatusPrsnlId;
        this.begEffectiveDtTm = begEffectiveDtTm;
        this.endEffectiveDtTm = endEffectiveDtTm;
        this.referenceTaskId = referenceTaskId;
        this.promptLongTextId = promptLongTextId;
    }
    public ProfileTaskR(ProfileTaskRId id, DiscreteTaskAssay discreteTaskAssay, BigDecimal versionNbr, BigDecimal groupCd, BigDecimal itemTypeFlag, BigDecimal pendingInd, BigDecimal repeatInd, BigDecimal sequence, BigDecimal dupChkMin, BigDecimal dupChkActionCd, Date updtDtTm, BigDecimal updtId, BigDecimal updtTask, BigDecimal updtCnt, BigDecimal updtApplctx, BigDecimal activeInd, BigDecimal postPromptInd, BigDecimal promptResourceCd, BigDecimal activeStatusCd, Date activeStatusDtTm, BigDecimal activeStatusPrsnlId, Date begEffectiveDtTm, Date endEffectiveDtTm, BigDecimal referenceTaskId, BigDecimal promptLongTextId, BigDecimal restrictDisplayInd, Date lastUtcTs) {
       this.id = id;
       this.discreteTaskAssay = discreteTaskAssay;
       this.versionNbr = versionNbr;
       this.groupCd = groupCd;
       this.itemTypeFlag = itemTypeFlag;
       this.pendingInd = pendingInd;
       this.repeatInd = repeatInd;
       this.sequence = sequence;
       this.dupChkMin = dupChkMin;
       this.dupChkActionCd = dupChkActionCd;
       this.updtDtTm = updtDtTm;
       this.updtId = updtId;
       this.updtTask = updtTask;
       this.updtCnt = updtCnt;
       this.updtApplctx = updtApplctx;
       this.activeInd = activeInd;
       this.postPromptInd = postPromptInd;
       this.promptResourceCd = promptResourceCd;
       this.activeStatusCd = activeStatusCd;
       this.activeStatusDtTm = activeStatusDtTm;
       this.activeStatusPrsnlId = activeStatusPrsnlId;
       this.begEffectiveDtTm = begEffectiveDtTm;
       this.endEffectiveDtTm = endEffectiveDtTm;
       this.referenceTaskId = referenceTaskId;
       this.promptLongTextId = promptLongTextId;
       this.restrictDisplayInd = restrictDisplayInd;
       this.lastUtcTs = lastUtcTs;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="catalogCd", column=@Column(name="CATALOG_CD", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="taskAssayCd", column=@Column(name="TASK_ASSAY_CD", nullable=false, precision=22, scale=0) ) } )
    public ProfileTaskRId getId() {
        return this.id;
    }
    
    public void setId(ProfileTaskRId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="TASK_ASSAY_CD", nullable=false, insertable=false, updatable=false)
    public DiscreteTaskAssay getDiscreteTaskAssay() {
        return this.discreteTaskAssay;
    }
    
    public void setDiscreteTaskAssay(DiscreteTaskAssay discreteTaskAssay) {
        this.discreteTaskAssay = discreteTaskAssay;
    }

    
    @Column(name="VERSION_NBR", precision=22, scale=0)
    public BigDecimal getVersionNbr() {
        return this.versionNbr;
    }
    
    public void setVersionNbr(BigDecimal versionNbr) {
        this.versionNbr = versionNbr;
    }

    
    @Column(name="GROUP_CD", nullable=false, precision=22, scale=0)
    public BigDecimal getGroupCd() {
        return this.groupCd;
    }
    
    public void setGroupCd(BigDecimal groupCd) {
        this.groupCd = groupCd;
    }

    
    @Column(name="ITEM_TYPE_FLAG", precision=22, scale=0)
    public BigDecimal getItemTypeFlag() {
        return this.itemTypeFlag;
    }
    
    public void setItemTypeFlag(BigDecimal itemTypeFlag) {
        this.itemTypeFlag = itemTypeFlag;
    }

    
    @Column(name="PENDING_IND", precision=22, scale=0)
    public BigDecimal getPendingInd() {
        return this.pendingInd;
    }
    
    public void setPendingInd(BigDecimal pendingInd) {
        this.pendingInd = pendingInd;
    }

    
    @Column(name="REPEAT_IND", precision=22, scale=0)
    public BigDecimal getRepeatInd() {
        return this.repeatInd;
    }
    
    public void setRepeatInd(BigDecimal repeatInd) {
        this.repeatInd = repeatInd;
    }

    
    @Column(name="SEQUENCE", precision=22, scale=0)
    public BigDecimal getSequence() {
        return this.sequence;
    }
    
    public void setSequence(BigDecimal sequence) {
        this.sequence = sequence;
    }

    
    @Column(name="DUP_CHK_MIN", precision=22, scale=0)
    public BigDecimal getDupChkMin() {
        return this.dupChkMin;
    }
    
    public void setDupChkMin(BigDecimal dupChkMin) {
        this.dupChkMin = dupChkMin;
    }

    
    @Column(name="DUP_CHK_ACTION_CD", nullable=false, precision=22, scale=0)
    public BigDecimal getDupChkActionCd() {
        return this.dupChkActionCd;
    }
    
    public void setDupChkActionCd(BigDecimal dupChkActionCd) {
        this.dupChkActionCd = dupChkActionCd;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="UPDT_DT_TM", nullable=false, length=7)
    public Date getUpdtDtTm() {
        return this.updtDtTm;
    }
    
    public void setUpdtDtTm(Date updtDtTm) {
        this.updtDtTm = updtDtTm;
    }

    
    @Column(name="UPDT_ID", nullable=false, precision=22, scale=0)
    public BigDecimal getUpdtId() {
        return this.updtId;
    }
    
    public void setUpdtId(BigDecimal updtId) {
        this.updtId = updtId;
    }

    
    @Column(name="UPDT_TASK", nullable=false, precision=22, scale=0)
    public BigDecimal getUpdtTask() {
        return this.updtTask;
    }
    
    public void setUpdtTask(BigDecimal updtTask) {
        this.updtTask = updtTask;
    }

    
    @Column(name="UPDT_CNT", nullable=false, precision=22, scale=0)
    public BigDecimal getUpdtCnt() {
        return this.updtCnt;
    }
    
    public void setUpdtCnt(BigDecimal updtCnt) {
        this.updtCnt = updtCnt;
    }

    
    @Column(name="UPDT_APPLCTX", nullable=false, precision=22, scale=0)
    public BigDecimal getUpdtApplctx() {
        return this.updtApplctx;
    }
    
    public void setUpdtApplctx(BigDecimal updtApplctx) {
        this.updtApplctx = updtApplctx;
    }

    
    @Column(name="ACTIVE_IND", precision=22, scale=0)
    public BigDecimal getActiveInd() {
        return this.activeInd;
    }
    
    public void setActiveInd(BigDecimal activeInd) {
        this.activeInd = activeInd;
    }

    
    @Column(name="POST_PROMPT_IND", precision=22, scale=0)
    public BigDecimal getPostPromptInd() {
        return this.postPromptInd;
    }
    
    public void setPostPromptInd(BigDecimal postPromptInd) {
        this.postPromptInd = postPromptInd;
    }

    
    @Column(name="PROMPT_RESOURCE_CD", nullable=false, precision=22, scale=0)
    public BigDecimal getPromptResourceCd() {
        return this.promptResourceCd;
    }
    
    public void setPromptResourceCd(BigDecimal promptResourceCd) {
        this.promptResourceCd = promptResourceCd;
    }

    
    @Column(name="ACTIVE_STATUS_CD", nullable=false, precision=22, scale=0)
    public BigDecimal getActiveStatusCd() {
        return this.activeStatusCd;
    }
    
    public void setActiveStatusCd(BigDecimal activeStatusCd) {
        this.activeStatusCd = activeStatusCd;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ACTIVE_STATUS_DT_TM", length=7)
    public Date getActiveStatusDtTm() {
        return this.activeStatusDtTm;
    }
    
    public void setActiveStatusDtTm(Date activeStatusDtTm) {
        this.activeStatusDtTm = activeStatusDtTm;
    }

    
    @Column(name="ACTIVE_STATUS_PRSNL_ID", nullable=false, precision=22, scale=0)
    public BigDecimal getActiveStatusPrsnlId() {
        return this.activeStatusPrsnlId;
    }
    
    public void setActiveStatusPrsnlId(BigDecimal activeStatusPrsnlId) {
        this.activeStatusPrsnlId = activeStatusPrsnlId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="BEG_EFFECTIVE_DT_TM", nullable=false, length=7)
    public Date getBegEffectiveDtTm() {
        return this.begEffectiveDtTm;
    }
    
    public void setBegEffectiveDtTm(Date begEffectiveDtTm) {
        this.begEffectiveDtTm = begEffectiveDtTm;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="END_EFFECTIVE_DT_TM", nullable=false, length=7)
    public Date getEndEffectiveDtTm() {
        return this.endEffectiveDtTm;
    }
    
    public void setEndEffectiveDtTm(Date endEffectiveDtTm) {
        this.endEffectiveDtTm = endEffectiveDtTm;
    }

    
    @Column(name="REFERENCE_TASK_ID", nullable=false, precision=22, scale=0)
    public BigDecimal getReferenceTaskId() {
        return this.referenceTaskId;
    }
    
    public void setReferenceTaskId(BigDecimal referenceTaskId) {
        this.referenceTaskId = referenceTaskId;
    }

    
    @Column(name="PROMPT_LONG_TEXT_ID", nullable=false, precision=22, scale=0)
    public BigDecimal getPromptLongTextId() {
        return this.promptLongTextId;
    }
    
    public void setPromptLongTextId(BigDecimal promptLongTextId) {
        this.promptLongTextId = promptLongTextId;
    }

    
    @Column(name="RESTRICT_DISPLAY_IND", precision=22, scale=0)
    public BigDecimal getRestrictDisplayInd() {
        return this.restrictDisplayInd;
    }
    
    public void setRestrictDisplayInd(BigDecimal restrictDisplayInd) {
        this.restrictDisplayInd = restrictDisplayInd;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_UTC_TS")
    public Date getLastUtcTs() {
        return this.lastUtcTs;
    }
    
    public void setLastUtcTs(Date lastUtcTs) {
        this.lastUtcTs = lastUtcTs;
    }




}


