package eshviewer.data;
// Generated Dec 11, 2017 9:52:44 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * V500EventCode generated by hbm2java
 */
@Entity
@Table(name="V500_EVENT_CODE"
    ,schema="V500"
)
public class V500EventCode  implements java.io.Serializable {


     private BigDecimal eventCd;
     private String eventCdDefinition;
     private String eventCdDescr;
     private String eventCdDisp;
     private String eventCdDispKey;
     private BigDecimal codeStatusCd;
     private String defDocmntAttributes;
     private BigDecimal defDocmntFormatCd;
     private BigDecimal defDocmntStorageCd;
     private BigDecimal defEventClassCd;
     private BigDecimal defEventConfidLevelCd;
     private BigDecimal defEventLevel;
     private BigDecimal eventAddAccessInd;
     private BigDecimal eventCdSubclassCd;
     private BigDecimal eventChgAccessInd;
     private String eventSetName;
     private BigDecimal retentionDays;
     private BigDecimal updtApplctx;
     private BigDecimal updtCnt;
     private Date updtDtTm;
     private BigDecimal updtId;
     private BigDecimal updtTask;
     private BigDecimal eventCodeStatusCd;
     private BigDecimal collatingSeq;
     private Date lastUtcTs;

    public V500EventCode() {
    }

	
    public V500EventCode(BigDecimal eventCd, BigDecimal codeStatusCd, BigDecimal defDocmntFormatCd, BigDecimal defDocmntStorageCd, BigDecimal defEventClassCd, BigDecimal defEventConfidLevelCd, BigDecimal eventCdSubclassCd, BigDecimal updtApplctx, BigDecimal updtCnt, Date updtDtTm, BigDecimal updtId, BigDecimal updtTask, BigDecimal eventCodeStatusCd, BigDecimal collatingSeq) {
        this.eventCd = eventCd;
        this.codeStatusCd = codeStatusCd;
        this.defDocmntFormatCd = defDocmntFormatCd;
        this.defDocmntStorageCd = defDocmntStorageCd;
        this.defEventClassCd = defEventClassCd;
        this.defEventConfidLevelCd = defEventConfidLevelCd;
        this.eventCdSubclassCd = eventCdSubclassCd;
        this.updtApplctx = updtApplctx;
        this.updtCnt = updtCnt;
        this.updtDtTm = updtDtTm;
        this.updtId = updtId;
        this.updtTask = updtTask;
        this.eventCodeStatusCd = eventCodeStatusCd;
        this.collatingSeq = collatingSeq;
    }
    public V500EventCode(BigDecimal eventCd, String eventCdDefinition, String eventCdDescr, String eventCdDisp, String eventCdDispKey, BigDecimal codeStatusCd, String defDocmntAttributes, BigDecimal defDocmntFormatCd, BigDecimal defDocmntStorageCd, BigDecimal defEventClassCd, BigDecimal defEventConfidLevelCd, BigDecimal defEventLevel, BigDecimal eventAddAccessInd, BigDecimal eventCdSubclassCd, BigDecimal eventChgAccessInd, String eventSetName, BigDecimal retentionDays, BigDecimal updtApplctx, BigDecimal updtCnt, Date updtDtTm, BigDecimal updtId, BigDecimal updtTask, BigDecimal eventCodeStatusCd, BigDecimal collatingSeq, Date lastUtcTs) {
       this.eventCd = eventCd;
       this.eventCdDefinition = eventCdDefinition;
       this.eventCdDescr = eventCdDescr;
       this.eventCdDisp = eventCdDisp;
       this.eventCdDispKey = eventCdDispKey;
       this.codeStatusCd = codeStatusCd;
       this.defDocmntAttributes = defDocmntAttributes;
       this.defDocmntFormatCd = defDocmntFormatCd;
       this.defDocmntStorageCd = defDocmntStorageCd;
       this.defEventClassCd = defEventClassCd;
       this.defEventConfidLevelCd = defEventConfidLevelCd;
       this.defEventLevel = defEventLevel;
       this.eventAddAccessInd = eventAddAccessInd;
       this.eventCdSubclassCd = eventCdSubclassCd;
       this.eventChgAccessInd = eventChgAccessInd;
       this.eventSetName = eventSetName;
       this.retentionDays = retentionDays;
       this.updtApplctx = updtApplctx;
       this.updtCnt = updtCnt;
       this.updtDtTm = updtDtTm;
       this.updtId = updtId;
       this.updtTask = updtTask;
       this.eventCodeStatusCd = eventCodeStatusCd;
       this.collatingSeq = collatingSeq;
       this.lastUtcTs = lastUtcTs;
    }
   
     @Id 

    
    @Column(name="EVENT_CD", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getEventCd() {
        return this.eventCd;
    }
    
    public void setEventCd(BigDecimal eventCd) {
        this.eventCd = eventCd;
    }

    
    @Column(name="EVENT_CD_DEFINITION", length=100)
    public String getEventCdDefinition() {
        return this.eventCdDefinition;
    }
    
    public void setEventCdDefinition(String eventCdDefinition) {
        this.eventCdDefinition = eventCdDefinition;
    }

    
    @Column(name="EVENT_CD_DESCR", length=60)
    public String getEventCdDescr() {
        return this.eventCdDescr;
    }
    
    public void setEventCdDescr(String eventCdDescr) {
        this.eventCdDescr = eventCdDescr;
    }

    
    @Column(name="EVENT_CD_DISP", length=40)
    public String getEventCdDisp() {
        return this.eventCdDisp;
    }
    
    public void setEventCdDisp(String eventCdDisp) {
        this.eventCdDisp = eventCdDisp;
    }

    
    @Column(name="EVENT_CD_DISP_KEY", length=40)
    public String getEventCdDispKey() {
        return this.eventCdDispKey;
    }
    
    public void setEventCdDispKey(String eventCdDispKey) {
        this.eventCdDispKey = eventCdDispKey;
    }

    
    @Column(name="CODE_STATUS_CD", nullable=false, precision=22, scale=0)
    public BigDecimal getCodeStatusCd() {
        return this.codeStatusCd;
    }
    
    public void setCodeStatusCd(BigDecimal codeStatusCd) {
        this.codeStatusCd = codeStatusCd;
    }

    
    @Column(name="DEF_DOCMNT_ATTRIBUTES")
    public String getDefDocmntAttributes() {
        return this.defDocmntAttributes;
    }
    
    public void setDefDocmntAttributes(String defDocmntAttributes) {
        this.defDocmntAttributes = defDocmntAttributes;
    }

    
    @Column(name="DEF_DOCMNT_FORMAT_CD", nullable=false, precision=22, scale=0)
    public BigDecimal getDefDocmntFormatCd() {
        return this.defDocmntFormatCd;
    }
    
    public void setDefDocmntFormatCd(BigDecimal defDocmntFormatCd) {
        this.defDocmntFormatCd = defDocmntFormatCd;
    }

    
    @Column(name="DEF_DOCMNT_STORAGE_CD", nullable=false, precision=22, scale=0)
    public BigDecimal getDefDocmntStorageCd() {
        return this.defDocmntStorageCd;
    }
    
    public void setDefDocmntStorageCd(BigDecimal defDocmntStorageCd) {
        this.defDocmntStorageCd = defDocmntStorageCd;
    }

    
    @Column(name="DEF_EVENT_CLASS_CD", nullable=false, precision=22, scale=0)
    public BigDecimal getDefEventClassCd() {
        return this.defEventClassCd;
    }
    
    public void setDefEventClassCd(BigDecimal defEventClassCd) {
        this.defEventClassCd = defEventClassCd;
    }

    
    @Column(name="DEF_EVENT_CONFID_LEVEL_CD", nullable=false, precision=22, scale=0)
    public BigDecimal getDefEventConfidLevelCd() {
        return this.defEventConfidLevelCd;
    }
    
    public void setDefEventConfidLevelCd(BigDecimal defEventConfidLevelCd) {
        this.defEventConfidLevelCd = defEventConfidLevelCd;
    }

    
    @Column(name="DEF_EVENT_LEVEL", precision=22, scale=0)
    public BigDecimal getDefEventLevel() {
        return this.defEventLevel;
    }
    
    public void setDefEventLevel(BigDecimal defEventLevel) {
        this.defEventLevel = defEventLevel;
    }

    
    @Column(name="EVENT_ADD_ACCESS_IND", precision=22, scale=0)
    public BigDecimal getEventAddAccessInd() {
        return this.eventAddAccessInd;
    }
    
    public void setEventAddAccessInd(BigDecimal eventAddAccessInd) {
        this.eventAddAccessInd = eventAddAccessInd;
    }

    
    @Column(name="EVENT_CD_SUBCLASS_CD", nullable=false, precision=22, scale=0)
    public BigDecimal getEventCdSubclassCd() {
        return this.eventCdSubclassCd;
    }
    
    public void setEventCdSubclassCd(BigDecimal eventCdSubclassCd) {
        this.eventCdSubclassCd = eventCdSubclassCd;
    }

    
    @Column(name="EVENT_CHG_ACCESS_IND", precision=22, scale=0)
    public BigDecimal getEventChgAccessInd() {
        return this.eventChgAccessInd;
    }
    
    public void setEventChgAccessInd(BigDecimal eventChgAccessInd) {
        this.eventChgAccessInd = eventChgAccessInd;
    }

    
    @Column(name="EVENT_SET_NAME", length=40)
    public String getEventSetName() {
        return this.eventSetName;
    }
    
    public void setEventSetName(String eventSetName) {
        this.eventSetName = eventSetName;
    }

    
    @Column(name="RETENTION_DAYS", precision=22, scale=0)
    public BigDecimal getRetentionDays() {
        return this.retentionDays;
    }
    
    public void setRetentionDays(BigDecimal retentionDays) {
        this.retentionDays = retentionDays;
    }

    
    @Column(name="UPDT_APPLCTX", nullable=false, precision=22, scale=0)
    public BigDecimal getUpdtApplctx() {
        return this.updtApplctx;
    }
    
    public void setUpdtApplctx(BigDecimal updtApplctx) {
        this.updtApplctx = updtApplctx;
    }

    
    @Column(name="UPDT_CNT", nullable=false, precision=22, scale=0)
    public BigDecimal getUpdtCnt() {
        return this.updtCnt;
    }
    
    public void setUpdtCnt(BigDecimal updtCnt) {
        this.updtCnt = updtCnt;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="UPDT_DT_TM", nullable=false, length=7)
    public Date getUpdtDtTm() {
        return this.updtDtTm;
    }
    
    public void setUpdtDtTm(Date updtDtTm) {
        this.updtDtTm = updtDtTm;
    }

    
    @Column(name="UPDT_ID", nullable=false, precision=22, scale=0)
    public BigDecimal getUpdtId() {
        return this.updtId;
    }
    
    public void setUpdtId(BigDecimal updtId) {
        this.updtId = updtId;
    }

    
    @Column(name="UPDT_TASK", nullable=false, precision=22, scale=0)
    public BigDecimal getUpdtTask() {
        return this.updtTask;
    }
    
    public void setUpdtTask(BigDecimal updtTask) {
        this.updtTask = updtTask;
    }

    
    @Column(name="EVENT_CODE_STATUS_CD", nullable=false, precision=22, scale=0)
    public BigDecimal getEventCodeStatusCd() {
        return this.eventCodeStatusCd;
    }
    
    public void setEventCodeStatusCd(BigDecimal eventCodeStatusCd) {
        this.eventCodeStatusCd = eventCodeStatusCd;
    }

    
    @Column(name="COLLATING_SEQ", nullable=false, precision=22, scale=0)
    public BigDecimal getCollatingSeq() {
        return this.collatingSeq;
    }
    
    public void setCollatingSeq(BigDecimal collatingSeq) {
        this.collatingSeq = collatingSeq;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_UTC_TS")
    public Date getLastUtcTs() {
        return this.lastUtcTs;
    }
    
    public void setLastUtcTs(Date lastUtcTs) {
        this.lastUtcTs = lastUtcTs;
    }




}


