package eshviewer.data;
// Generated Dec 11, 2017 9:52:44 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * V500EventSetCode generated by hbm2java
 */
@Entity
@Table(name="V500_EVENT_SET_CODE"
    ,schema="V500"
    , uniqueConstraints = @UniqueConstraint(columnNames="EVENT_SET_NAME") 
)
public class V500EventSetCode  implements java.io.Serializable {


     private BigDecimal eventSetCd;
     private BigDecimal accumulationInd;
     private BigDecimal categoryFlag;
     private String eventSetCdDefinition;
     private String eventSetCdDescr;
     private String eventSetCdDisp;
     private String eventSetCdDispKey;
     private BigDecimal codeStatusCd;
     private String combineFormat;
     private String eventSetColorName;
     private String eventSetIconName;
     private String eventSetName;
     private String eventSetNameKey;
     private BigDecimal eventSetStatusCd;
     private BigDecimal groupingRuleFlag;
     private BigDecimal leafEventCdCount;
     private BigDecimal operationDisplayFlag;
     private String operationFormula;
     private BigDecimal primitiveEventSetCount;
     private BigDecimal showIfNoDataInd;
     private BigDecimal updtApplctx;
     private BigDecimal updtCnt;
     private Date updtDtTm;
     private BigDecimal updtId;
     private BigDecimal updtTask;
     private BigDecimal displayAssociationInd;
     private Date lastUtcTs;

    public V500EventSetCode() {
    }

	
    public V500EventSetCode(BigDecimal eventSetCd, BigDecimal codeStatusCd, String eventSetName, BigDecimal eventSetStatusCd, BigDecimal updtApplctx, BigDecimal updtCnt, Date updtDtTm, BigDecimal updtId, BigDecimal updtTask, BigDecimal displayAssociationInd) {
        this.eventSetCd = eventSetCd;
        this.codeStatusCd = codeStatusCd;
        this.eventSetName = eventSetName;
        this.eventSetStatusCd = eventSetStatusCd;
        this.updtApplctx = updtApplctx;
        this.updtCnt = updtCnt;
        this.updtDtTm = updtDtTm;
        this.updtId = updtId;
        this.updtTask = updtTask;
        this.displayAssociationInd = displayAssociationInd;
    }
    public V500EventSetCode(BigDecimal eventSetCd, BigDecimal accumulationInd, BigDecimal categoryFlag, String eventSetCdDefinition, String eventSetCdDescr, String eventSetCdDisp, String eventSetCdDispKey, BigDecimal codeStatusCd, String combineFormat, String eventSetColorName, String eventSetIconName, String eventSetName, String eventSetNameKey, BigDecimal eventSetStatusCd, BigDecimal groupingRuleFlag, BigDecimal leafEventCdCount, BigDecimal operationDisplayFlag, String operationFormula, BigDecimal primitiveEventSetCount, BigDecimal showIfNoDataInd, BigDecimal updtApplctx, BigDecimal updtCnt, Date updtDtTm, BigDecimal updtId, BigDecimal updtTask, BigDecimal displayAssociationInd, Date lastUtcTs) {
       this.eventSetCd = eventSetCd;
       this.accumulationInd = accumulationInd;
       this.categoryFlag = categoryFlag;
       this.eventSetCdDefinition = eventSetCdDefinition;
       this.eventSetCdDescr = eventSetCdDescr;
       this.eventSetCdDisp = eventSetCdDisp;
       this.eventSetCdDispKey = eventSetCdDispKey;
       this.codeStatusCd = codeStatusCd;
       this.combineFormat = combineFormat;
       this.eventSetColorName = eventSetColorName;
       this.eventSetIconName = eventSetIconName;
       this.eventSetName = eventSetName;
       this.eventSetNameKey = eventSetNameKey;
       this.eventSetStatusCd = eventSetStatusCd;
       this.groupingRuleFlag = groupingRuleFlag;
       this.leafEventCdCount = leafEventCdCount;
       this.operationDisplayFlag = operationDisplayFlag;
       this.operationFormula = operationFormula;
       this.primitiveEventSetCount = primitiveEventSetCount;
       this.showIfNoDataInd = showIfNoDataInd;
       this.updtApplctx = updtApplctx;
       this.updtCnt = updtCnt;
       this.updtDtTm = updtDtTm;
       this.updtId = updtId;
       this.updtTask = updtTask;
       this.displayAssociationInd = displayAssociationInd;
       this.lastUtcTs = lastUtcTs;
    }
   
     @Id 

    
    @Column(name="EVENT_SET_CD", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getEventSetCd() {
        return this.eventSetCd;
    }
    
    public void setEventSetCd(BigDecimal eventSetCd) {
        this.eventSetCd = eventSetCd;
    }

    
    @Column(name="ACCUMULATION_IND", precision=22, scale=0)
    public BigDecimal getAccumulationInd() {
        return this.accumulationInd;
    }
    
    public void setAccumulationInd(BigDecimal accumulationInd) {
        this.accumulationInd = accumulationInd;
    }

    
    @Column(name="CATEGORY_FLAG", precision=22, scale=0)
    public BigDecimal getCategoryFlag() {
        return this.categoryFlag;
    }
    
    public void setCategoryFlag(BigDecimal categoryFlag) {
        this.categoryFlag = categoryFlag;
    }

    
    @Column(name="EVENT_SET_CD_DEFINITION", length=100)
    public String getEventSetCdDefinition() {
        return this.eventSetCdDefinition;
    }
    
    public void setEventSetCdDefinition(String eventSetCdDefinition) {
        this.eventSetCdDefinition = eventSetCdDefinition;
    }

    
    @Column(name="EVENT_SET_CD_DESCR", length=60)
    public String getEventSetCdDescr() {
        return this.eventSetCdDescr;
    }
    
    public void setEventSetCdDescr(String eventSetCdDescr) {
        this.eventSetCdDescr = eventSetCdDescr;
    }

    
    @Column(name="EVENT_SET_CD_DISP", length=40)
    public String getEventSetCdDisp() {
        return this.eventSetCdDisp;
    }
    
    public void setEventSetCdDisp(String eventSetCdDisp) {
        this.eventSetCdDisp = eventSetCdDisp;
    }

    
    @Column(name="EVENT_SET_CD_DISP_KEY", length=40)
    public String getEventSetCdDispKey() {
        return this.eventSetCdDispKey;
    }
    
    public void setEventSetCdDispKey(String eventSetCdDispKey) {
        this.eventSetCdDispKey = eventSetCdDispKey;
    }

    
    @Column(name="CODE_STATUS_CD", nullable=false, precision=22, scale=0)
    public BigDecimal getCodeStatusCd() {
        return this.codeStatusCd;
    }
    
    public void setCodeStatusCd(BigDecimal codeStatusCd) {
        this.codeStatusCd = codeStatusCd;
    }

    
    @Column(name="COMBINE_FORMAT", length=200)
    public String getCombineFormat() {
        return this.combineFormat;
    }
    
    public void setCombineFormat(String combineFormat) {
        this.combineFormat = combineFormat;
    }

    
    @Column(name="EVENT_SET_COLOR_NAME", length=16)
    public String getEventSetColorName() {
        return this.eventSetColorName;
    }
    
    public void setEventSetColorName(String eventSetColorName) {
        this.eventSetColorName = eventSetColorName;
    }

    
    @Column(name="EVENT_SET_ICON_NAME", length=16)
    public String getEventSetIconName() {
        return this.eventSetIconName;
    }
    
    public void setEventSetIconName(String eventSetIconName) {
        this.eventSetIconName = eventSetIconName;
    }

    
    @Column(name="EVENT_SET_NAME", unique=true, nullable=false, length=40)
    public String getEventSetName() {
        return this.eventSetName;
    }
    
    public void setEventSetName(String eventSetName) {
        this.eventSetName = eventSetName;
    }

    
    @Column(name="EVENT_SET_NAME_KEY", length=40)
    public String getEventSetNameKey() {
        return this.eventSetNameKey;
    }
    
    public void setEventSetNameKey(String eventSetNameKey) {
        this.eventSetNameKey = eventSetNameKey;
    }

    
    @Column(name="EVENT_SET_STATUS_CD", nullable=false, precision=22, scale=0)
    public BigDecimal getEventSetStatusCd() {
        return this.eventSetStatusCd;
    }
    
    public void setEventSetStatusCd(BigDecimal eventSetStatusCd) {
        this.eventSetStatusCd = eventSetStatusCd;
    }

    
    @Column(name="GROUPING_RULE_FLAG", precision=22, scale=0)
    public BigDecimal getGroupingRuleFlag() {
        return this.groupingRuleFlag;
    }
    
    public void setGroupingRuleFlag(BigDecimal groupingRuleFlag) {
        this.groupingRuleFlag = groupingRuleFlag;
    }

    
    @Column(name="LEAF_EVENT_CD_COUNT", precision=22, scale=0)
    public BigDecimal getLeafEventCdCount() {
        return this.leafEventCdCount;
    }
    
    public void setLeafEventCdCount(BigDecimal leafEventCdCount) {
        this.leafEventCdCount = leafEventCdCount;
    }

    
    @Column(name="OPERATION_DISPLAY_FLAG", precision=22, scale=0)
    public BigDecimal getOperationDisplayFlag() {
        return this.operationDisplayFlag;
    }
    
    public void setOperationDisplayFlag(BigDecimal operationDisplayFlag) {
        this.operationDisplayFlag = operationDisplayFlag;
    }

    
    @Column(name="OPERATION_FORMULA", length=200)
    public String getOperationFormula() {
        return this.operationFormula;
    }
    
    public void setOperationFormula(String operationFormula) {
        this.operationFormula = operationFormula;
    }

    
    @Column(name="PRIMITIVE_EVENT_SET_COUNT", precision=22, scale=0)
    public BigDecimal getPrimitiveEventSetCount() {
        return this.primitiveEventSetCount;
    }
    
    public void setPrimitiveEventSetCount(BigDecimal primitiveEventSetCount) {
        this.primitiveEventSetCount = primitiveEventSetCount;
    }

    
    @Column(name="SHOW_IF_NO_DATA_IND", precision=22, scale=0)
    public BigDecimal getShowIfNoDataInd() {
        return this.showIfNoDataInd;
    }
    
    public void setShowIfNoDataInd(BigDecimal showIfNoDataInd) {
        this.showIfNoDataInd = showIfNoDataInd;
    }

    
    @Column(name="UPDT_APPLCTX", nullable=false, precision=22, scale=0)
    public BigDecimal getUpdtApplctx() {
        return this.updtApplctx;
    }
    
    public void setUpdtApplctx(BigDecimal updtApplctx) {
        this.updtApplctx = updtApplctx;
    }

    
    @Column(name="UPDT_CNT", nullable=false, precision=22, scale=0)
    public BigDecimal getUpdtCnt() {
        return this.updtCnt;
    }
    
    public void setUpdtCnt(BigDecimal updtCnt) {
        this.updtCnt = updtCnt;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="UPDT_DT_TM", nullable=false, length=7)
    public Date getUpdtDtTm() {
        return this.updtDtTm;
    }
    
    public void setUpdtDtTm(Date updtDtTm) {
        this.updtDtTm = updtDtTm;
    }

    
    @Column(name="UPDT_ID", nullable=false, precision=22, scale=0)
    public BigDecimal getUpdtId() {
        return this.updtId;
    }
    
    public void setUpdtId(BigDecimal updtId) {
        this.updtId = updtId;
    }

    
    @Column(name="UPDT_TASK", nullable=false, precision=22, scale=0)
    public BigDecimal getUpdtTask() {
        return this.updtTask;
    }
    
    public void setUpdtTask(BigDecimal updtTask) {
        this.updtTask = updtTask;
    }

    
    @Column(name="DISPLAY_ASSOCIATION_IND", nullable=false, precision=22, scale=0)
    public BigDecimal getDisplayAssociationInd() {
        return this.displayAssociationInd;
    }
    
    public void setDisplayAssociationInd(BigDecimal displayAssociationInd) {
        this.displayAssociationInd = displayAssociationInd;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_UTC_TS")
    public Date getLastUtcTs() {
        return this.lastUtcTs;
    }
    
    public void setLastUtcTs(Date lastUtcTs) {
        this.lastUtcTs = lastUtcTs;
    }




}


