package eshviewer.data;
// Generated Dec 11, 2017 9:52:44 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * V500EventSetExplode generated by hbm2java
 */
@Entity
@Table(name="V500_EVENT_SET_EXPLODE"
    ,schema="V500"
)
public class V500EventSetExplode  implements java.io.Serializable {


     private V500EventSetExplodeId id;

    public V500EventSetExplode() {
    }

    public V500EventSetExplode(V500EventSetExplodeId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="eventCd", column=@Column(name="EVENT_CD", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="eventSetCd", column=@Column(name="EVENT_SET_CD", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="eventSetStatusCd", column=@Column(name="EVENT_SET_STATUS_CD", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="updtDtTm", column=@Column(name="UPDT_DT_TM", nullable=false, length=7) ), 
        @AttributeOverride(name="updtTask", column=@Column(name="UPDT_TASK", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="updtId", column=@Column(name="UPDT_ID", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="updtCnt", column=@Column(name="UPDT_CNT", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="updtApplctx", column=@Column(name="UPDT_APPLCTX", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="eventSetLevel", column=@Column(name="EVENT_SET_LEVEL", precision=22, scale=0) ), 
        @AttributeOverride(name="lastUtcTs", column=@Column(name="LAST_UTC_TS") ) } )
    public V500EventSetExplodeId getId() {
        return this.id;
    }
    
    public void setId(V500EventSetExplodeId id) {
        this.id = id;
    }




}


