
REM  CREATE TABLE "V500"."ASDF" ("A" VARCHAR2(1)) PCTFREE 10 PCTUSED 40 
REM  INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 
REM  1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE 
REM  "USERS" LOGGING NOCOMPRESS ;
REM  ... 0 rows
REM  CREATE TABLE "V500"."CODE_VALUE" ("CODE_VALUE" NUMBER NOT NULL 
REM  ENABLE, "CODE_SET" NUMBER NOT NULL ENABLE, "CDF_MEANING" 
REM  VARCHAR2(12), "DISPLAY" VARCHAR2(100), "DISPLAY_KEY" VARCHAR2(100), 
REM  "DESCRIPTION" VARCHAR2(100), "DEFINITION" VARCHAR2(100), 
REM  "COLLATION_SEQ" NUMBER, "ACTIVE_TYPE_CD" NUMBER NOT NULL ENABLE, 
REM  "ACTIVE_IND" NUMBER, "ACTIVE_DT_TM" DATE, "INACTIVE_DT_TM" DATE, 
REM  "UPDT_DT_TM" DATE NOT NULL ENABLE, "UPDT_ID" NUMBER NOT NULL ENABLE, 
REM  "UPDT_CNT" NUMBER NOT NULL ENABLE, "UPDT_TASK" NUMBER NOT NULL 
REM  ENABLE, "UPDT_APPLCTX" NUMBER NOT NULL ENABLE, 
REM  "BEGIN_EFFECTIVE_DT_TM" DATE, "END_EFFECTIVE_DT_TM" DATE NOT NULL 
REM  ENABLE, "DATA_STATUS_CD" NUMBER NOT NULL ENABLE, "DATA_STATUS_DT_TM" 
REM  DATE, "DATA_STATUS_PRSNL_ID" NUMBER NOT NULL ENABLE, 
REM  "ACTIVE_STATUS_PRSNL_ID" NUMBER NOT NULL ENABLE, "CKI" VARCHAR2(255), 
REM  "DISPLAY_KEY_NLS" VARCHAR2(255), "CONCEPT_CKI" VARCHAR2(255), 
REM  "DISPLAY_KEY_A_NLS" VARCHAR2(160), "LAST_UTC_TS" TIMESTAMP (9), 
REM  "CLU_SUBKEY1_FLAG" NUMBER) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
REM  255 STORAGE(INITIAL 88080384 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 
REM  FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" LOGGING 
REM  NOCOMPRESS ;
REM  ALTER TABLE "V500"."CODE_VALUE" MODIFY ("CODE_VALUE" DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."CODE_VALUE" MODIFY ("CODE_SET" DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."CODE_VALUE" MODIFY ("COLLATION_SEQ" DEFAULT 0) ;
REM  ALTER TABLE "V500"."CODE_VALUE" MODIFY ("ACTIVE_TYPE_CD" DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."CODE_VALUE" MODIFY ("UPDT_DT_TM" DEFAULT SYSDATE 
REM  ) ;
REM  ALTER TABLE "V500"."CODE_VALUE" MODIFY ("UPDT_ID" DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."CODE_VALUE" MODIFY ("UPDT_CNT" DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."CODE_VALUE" MODIFY ("UPDT_TASK" DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."CODE_VALUE" MODIFY ("UPDT_APPLCTX" DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."CODE_VALUE" MODIFY ("BEGIN_EFFECTIVE_DT_TM" 
REM  DEFAULT SYSDATE) ;
REM  ALTER TABLE "V500"."CODE_VALUE" MODIFY ("END_EFFECTIVE_DT_TM" DEFAULT 
REM  TO_DATE('12/31/2100 00:00:00','MM/DD/YYYY HH24:MI:SS') ) ;
REM  ALTER TABLE "V500"."CODE_VALUE" MODIFY ("DATA_STATUS_CD" DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."CODE_VALUE" MODIFY ("DATA_STATUS_PRSNL_ID" 
REM  DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."CODE_VALUE" MODIFY ("ACTIVE_STATUS_PRSNL_ID" 
REM  DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."CODE_VALUE" MODIFY ("CONCEPT_CKI" DEFAULT ' ') ;
REM  ... 392229 rows
CONNECT V500;
CREATE UNIQUE INDEX "V500"."XPKCODE_VALUE" ON "CODE_VALUE" ("CODE_VALUE" ) 
PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 10485760 NEXT 1048576 
MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE 
"USERS" LOGGING ;
CREATE INDEX "V500"."XIE1CODE_VALUE" ON "CODE_VALUE" ("CODE_SET" , 
"COLLATION_SEQ" , "DISPLAY_KEY" ) PCTFREE 10 INITRANS 2 MAXTRANS 255 
STORAGE(INITIAL 22020096 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST 
GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" LOGGING ;
CREATE INDEX "V500"."XAK2CODE_VALUE" ON "CODE_VALUE" ("CKI" ) PCTFREE 10 
INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 
FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" 
LOGGING ;
CREATE INDEX "V500"."XIE5CODE_VALUE" ON "CODE_VALUE" ("CONCEPT_CKI" ) 
PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 6291456 NEXT 1048576 
MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE 
"USERS" LOGGING ;
CREATE INDEX "V500"."XIE6CODE_VALUE" ON "CODE_VALUE" ("UPDT_DT_TM" ) 
PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 12582912 NEXT 1048576 
MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE 
"USERS" LOGGING ;
CREATE UNIQUE INDEX "V500"."XAK1CODE_VALUE" ON "CODE_VALUE" ("CODE_SET" , 
"CODE_VALUE" ) PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 13631488 
NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL 
DEFAULT) TABLESPACE "USERS" LOGGING ;
CREATE INDEX "V500"."XIE2CODE_VALUE" ON "CODE_VALUE" ("CODE_SET" , 
"DISPLAY_KEY" ) PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 
20971520 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 
BUFFER_POOL DEFAULT) TABLESPACE "USERS" LOGGING ;
CREATE INDEX "V500"."XIE3CODE_VALUE" ON "CODE_VALUE" ("DISPLAY_KEY" ) 
PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 17825792 NEXT 1048576 
MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE 
"USERS" LOGGING ;
CREATE INDEX "V500"."XIF28CODE_VALUE" ON "CODE_VALUE" ("CODE_SET" , 
"CDF_MEANING" ) PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 
13631488 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 
BUFFER_POOL DEFAULT) TABLESPACE "USERS" LOGGING ;
CREATE INDEX "V500"."XIE9CODE_VALUE" ON "CODE_VALUE" ("CODE_SET" , 
"DESCRIPTION" ) PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 
24117248 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 
BUFFER_POOL DEFAULT) TABLESPACE "USERS" LOGGING ;
CREATE INDEX "V500"."XIE8CODE_VALUE" ON "CODE_VALUE" ("CODE_SET" , 
"DISPLAY" ) PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 23068672 
NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL 
DEFAULT) TABLESPACE "USERS" LOGGING ;
CREATE INDEX "V500"."XCERCODE_VALUE0619" ON "CODE_VALUE" ("LAST_UTC_TS" ) 
PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 9437184 NEXT 1048576 
MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE 
"USERS" LOGGING ;
REM  ALTER TABLE "V500"."CODE_VALUE" ADD CONSTRAINT "XPKCODE_VALUE" 
REM  PRIMARY KEY ("CODE_VALUE") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 
REM  255 STORAGE(INITIAL 10485760 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 
REM  FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" LOGGING 
REM  ENABLE ;
REM  ALTER TABLE "V500"."CODE_VALUE" ADD SUPPLEMENTAL LOG GROUP 
REM  "GGS_112050" ("CODE_VALUE") ALWAYS ;
REM  CREATE TABLE "V500"."CODE_VALUE_2" ("CODE_VALUE" NUMBER NOT NULL 
REM  ENABLE, "CODE_SET" NUMBER NOT NULL ENABLE, "CDF_MEANING" 
REM  VARCHAR2(12), "DISPLAY" VARCHAR2(40), "DISPLAY_KEY" VARCHAR2(40), 
REM  "DESCRIPTION" VARCHAR2(60), "DEFINITION" VARCHAR2(100), 
REM  "COLLATION_SEQ" NUMBER, "ACTIVE_TYPE_CD" NUMBER NOT NULL ENABLE, 
REM  "ACTIVE_IND" NUMBER, "ACTIVE_DT_TM" DATE, "INACTIVE_DT_TM" DATE, 
REM  "UPDT_DT_TM" DATE NOT NULL ENABLE, "UPDT_ID" NUMBER NOT NULL ENABLE, 
REM  "UPDT_CNT" NUMBER NOT NULL ENABLE, "UPDT_TASK" NUMBER NOT NULL 
REM  ENABLE, "UPDT_APPLCTX" NUMBER NOT NULL ENABLE, 
REM  "BEGIN_EFFECTIVE_DT_TM" DATE, "END_EFFECTIVE_DT_TM" DATE NOT NULL 
REM  ENABLE, "DATA_STATUS_CD" NUMBER NOT NULL ENABLE, "DATA_STATUS_DT_TM" 
REM  DATE, "DATA_STATUS_PRSNL_ID" NUMBER NOT NULL ENABLE, 
REM  "ACTIVE_STATUS_PRSNL_ID" NUMBER NOT NULL ENABLE, "CKI" VARCHAR2(255), 
REM  "DISPLAY_KEY_NLS" VARCHAR2(255), "CONCEPT_CKI" VARCHAR2(255), 
REM  "DISPLAY_KEY_A_NLS" VARCHAR2(160), "LAST_UTC_TS" TIMESTAMP (9), 
REM  "CLU_SUBKEY1_FLAG" NUMBER) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
REM  255 STORAGE(INITIAL 82837504 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 
REM  FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" LOGGING 
REM  NOCOMPRESS ;
REM  ... 370154 rows
REM  CREATE TABLE "V500"."CODE_VALUE_ALIAS" ("CODE_SET" NUMBER NOT NULL 
REM  ENABLE, "CONTRIBUTOR_SOURCE_CD" NUMBER NOT NULL ENABLE, "ALIAS" 
REM  VARCHAR2(255) NOT NULL ENABLE, "CODE_VALUE" NUMBER NOT NULL ENABLE, 
REM  "PRIMARY_IND" NUMBER, "UPDT_DT_TM" DATE NOT NULL ENABLE, "UPDT_ID" 
REM  NUMBER NOT NULL ENABLE, "UPDT_TASK" NUMBER NOT NULL ENABLE, 
REM  "UPDT_CNT" NUMBER NOT NULL ENABLE, "UPDT_APPLCTX" NUMBER NOT NULL 
REM  ENABLE, "ALIAS_TYPE_MEANING" VARCHAR2(12), "LAST_UTC_TS" TIMESTAMP 
REM  (9)) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 
REM  9437184 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 
REM  BUFFER_POOL DEFAULT) TABLESPACE "USERS" LOGGING NOCOMPRESS ;
REM  ALTER TABLE "V500"."CODE_VALUE_ALIAS" MODIFY ("CODE_SET" DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."CODE_VALUE_ALIAS" MODIFY ("CONTRIBUTOR_SOURCE_CD" 
REM  DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."CODE_VALUE_ALIAS" MODIFY ("ALIAS" DEFAULT ' ' ) ;
REM  ALTER TABLE "V500"."CODE_VALUE_ALIAS" MODIFY ("CODE_VALUE" DEFAULT 0 
REM  ) ;
REM  ALTER TABLE "V500"."CODE_VALUE_ALIAS" MODIFY ("UPDT_DT_TM" DEFAULT 
REM  SYSDATE ) ;
REM  ALTER TABLE "V500"."CODE_VALUE_ALIAS" MODIFY ("UPDT_ID" DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."CODE_VALUE_ALIAS" MODIFY ("UPDT_TASK" DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."CODE_VALUE_ALIAS" MODIFY ("UPDT_CNT" DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."CODE_VALUE_ALIAS" MODIFY ("UPDT_APPLCTX" DEFAULT 
REM  0 ) ;
REM  ... 121881 rows
CREATE UNIQUE INDEX "V500"."XAK1CODE_VALUE_ALIAS" ON "CODE_VALUE_ALIAS" 
("ALIAS" , "CODE_SET" , "CONTRIBUTOR_SOURCE_CD" , "ALIAS_TYPE_MEANING" ) 
PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 6291456 NEXT 1048576 
MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE 
"USERS" LOGGING ;
CREATE INDEX "V500"."XIE3CODE_VALUE_ALIAS" ON "CODE_VALUE_ALIAS" 
("UPDT_DT_TM" ) PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 4194304 
NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL 
DEFAULT) TABLESPACE "USERS" LOGGING ;
CREATE INDEX "V500"."XIE1CODE_VALUE_ALIAS" ON "CODE_VALUE_ALIAS" 
("CODE_SET" , "CONTRIBUTOR_SOURCE_CD" ) PCTFREE 10 INITRANS 2 MAXTRANS 255 
STORAGE(INITIAL 5242880 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST 
GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" LOGGING ;
CREATE INDEX "V500"."XIE2CODE_VALUE_ALIAS" ON "CODE_VALUE_ALIAS" 
("CODE_VALUE" ) PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 4194304 
NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL 
DEFAULT) TABLESPACE "USERS" LOGGING ;
CREATE INDEX "V500"."XCERCODE_VALUE_ALI0036" ON "CODE_VALUE_ALIAS" 
("LAST_UTC_TS" ) PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 786432 
NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL 
DEFAULT) TABLESPACE "USERS" LOGGING ;
REM  ALTER TABLE "V500"."CODE_VALUE_ALIAS" ADD SUPPLEMENTAL LOG GROUP 
REM  "GGS_112051" ("CODE_SET", "CONTRIBUTOR_SOURCE_CD", "ALIAS", 
REM  "ALIAS_TYPE_MEANING") ALWAYS ;
REM  CREATE TABLE "V500"."CODE_VALUE_EVENT_R" ("EVENT_CD" FLOAT(126) NOT 
REM  NULL ENABLE, "PARENT_CD" FLOAT(126) NOT NULL ENABLE, "FLEX1_CD" 
REM  NUMBER NOT NULL ENABLE, "FLEX2_CD" NUMBER NOT NULL ENABLE, "FLEX3_CD" 
REM  NUMBER NOT NULL ENABLE, "FLEX4_CD" NUMBER NOT NULL ENABLE, 
REM  "UPDT_DT_TM" DATE NOT NULL ENABLE, "FLEX5_CD" NUMBER NOT NULL ENABLE, 
REM  "UPDT_ID" FLOAT(126) NOT NULL ENABLE, "UPDT_TASK" NUMBER NOT NULL 
REM  ENABLE, "UPDT_CNT" NUMBER NOT NULL ENABLE, "UPDT_APPLCTX" NUMBER NOT 
REM  NULL ENABLE, "LAST_UTC_TS" TIMESTAMP (9)) PCTFREE 10 PCTUSED 40 
REM  INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 1048576 NEXT 1048576 
REM  MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) 
REM  TABLESPACE "USERS" LOGGING NOCOMPRESS ;
REM  ALTER TABLE "V500"."CODE_VALUE_EVENT_R" MODIFY ("EVENT_CD" DEFAULT 0 
REM  ) ;
REM  ALTER TABLE "V500"."CODE_VALUE_EVENT_R" MODIFY ("PARENT_CD" DEFAULT 0 
REM  ) ;
REM  ALTER TABLE "V500"."CODE_VALUE_EVENT_R" MODIFY ("FLEX1_CD" DEFAULT 0 
REM  ) ;
REM  ALTER TABLE "V500"."CODE_VALUE_EVENT_R" MODIFY ("FLEX2_CD" DEFAULT 0 
REM  ) ;
REM  ALTER TABLE "V500"."CODE_VALUE_EVENT_R" MODIFY ("FLEX3_CD" DEFAULT 0 
REM  ) ;
REM  ALTER TABLE "V500"."CODE_VALUE_EVENT_R" MODIFY ("FLEX4_CD" DEFAULT 0 
REM  ) ;
REM  ALTER TABLE "V500"."CODE_VALUE_EVENT_R" MODIFY ("UPDT_DT_TM" DEFAULT 
REM  SYSDATE ) ;
REM  ALTER TABLE "V500"."CODE_VALUE_EVENT_R" MODIFY ("FLEX5_CD" DEFAULT 0 
REM  ) ;
REM  ALTER TABLE "V500"."CODE_VALUE_EVENT_R" MODIFY ("UPDT_ID" DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."CODE_VALUE_EVENT_R" MODIFY ("UPDT_TASK" DEFAULT 0 
REM  ) ;
REM  ALTER TABLE "V500"."CODE_VALUE_EVENT_R" MODIFY ("UPDT_CNT" DEFAULT 0 
REM  ) ;
REM  ALTER TABLE "V500"."CODE_VALUE_EVENT_R" MODIFY ("UPDT_APPLCTX" 
REM  DEFAULT 0 ) ;
REM  ... 14500 rows
CREATE UNIQUE INDEX "V500"."XPKCODE_VALUE_EVENT_R" ON "CODE_VALUE_EVENT_R" 
("PARENT_CD" , "FLEX1_CD" , "FLEX2_CD" , "FLEX3_CD" , "FLEX4_CD" , 
"FLEX5_CD" ) PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 720896 
NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL 
DEFAULT) TABLESPACE "USERS" LOGGING ;
CREATE INDEX "V500"."XIE1CODE_VALUE_EVENT_R" ON "CODE_VALUE_EVENT_R" 
("EVENT_CD" ) PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 458752 
NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL 
DEFAULT) TABLESPACE "USERS" LOGGING ;
CREATE INDEX "V500"."XCERCODE_VALUE_EVE2215" ON "CODE_VALUE_EVENT_R" 
("LAST_UTC_TS" ) PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 131072 
NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL 
DEFAULT) TABLESPACE "USERS" LOGGING ;
REM  ALTER TABLE "V500"."CODE_VALUE_EVENT_R" ADD SUPPLEMENTAL LOG GROUP 
REM  "GGS_112052" ("PARENT_CD", "FLEX1_CD", "FLEX2_CD", "FLEX3_CD", 
REM  "FLEX4_CD", "FLEX5_CD") ALWAYS ;
REM  CREATE TABLE "V500"."CODE_VALUE_SET" ("CODE_SET" NUMBER NOT NULL 
REM  ENABLE, "DISPLAY" VARCHAR2(40), "DISPLAY_KEY" VARCHAR2(40), 
REM  "DESCRIPTION" VARCHAR2(60), "DEFINITION" VARCHAR2(500), "TABLE_NAME" 
REM  VARCHAR2(32), "CONTRIBUTOR" VARCHAR2(18), "OWNER_MODULE" 
REM  VARCHAR2(12), "CACHE_IND" NUMBER, "EXTENSION_IND" NUMBER, 
REM  "ADD_ACCESS_IND" NUMBER, "CHG_ACCESS_IND" NUMBER, "DEL_ACCESS_IND" 
REM  NUMBER, "INQ_ACCESS_IND" NUMBER, "DOMAIN_QUALIFIER_IND" NUMBER, 
REM  "DOMAIN_CODE_SET" NUMBER, "UPDT_DT_TM" DATE NOT NULL ENABLE, 
REM  "UPDT_ID" NUMBER NOT NULL ENABLE, "UPDT_CNT" NUMBER NOT NULL ENABLE, 
REM  "UPDT_TASK" NUMBER NOT NULL ENABLE, "UPDT_APPLCTX" NUMBER NOT NULL 
REM  ENABLE, "CODE_SET_HITS" NUMBER, "CODE_VALUES_CNT" NUMBER, 
REM  "DEF_DUP_RULE_FLAG" NUMBER, "CDF_MEANING_DUP_IND" NUMBER, 
REM  "DISPLAY_KEY_DUP_IND" NUMBER, "ACTIVE_IND_DUP_IND" NUMBER, 
REM  "DISPLAY_DUP_IND" NUMBER, "ALIAS_DUP_IND" NUMBER, 
REM  "DEFINITION_DUP_IND" NUMBER, "LAST_UTC_TS" TIMESTAMP (9)) PCTFREE 10 
REM  PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 917504 NEXT 
REM  1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL 
REM  DEFAULT) TABLESPACE "USERS" LOGGING NOCOMPRESS ;
REM  ALTER TABLE "V500"."CODE_VALUE_SET" MODIFY ("CODE_SET" DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."CODE_VALUE_SET" MODIFY ("UPDT_DT_TM" DEFAULT 
REM  SYSDATE ) ;
REM  ALTER TABLE "V500"."CODE_VALUE_SET" MODIFY ("UPDT_ID" DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."CODE_VALUE_SET" MODIFY ("UPDT_CNT" DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."CODE_VALUE_SET" MODIFY ("UPDT_TASK" DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."CODE_VALUE_SET" MODIFY ("UPDT_APPLCTX" DEFAULT 0 
REM  ) ;
REM  ALTER TABLE "V500"."CODE_VALUE_SET" MODIFY ("ALIAS_DUP_IND" DEFAULT 
REM  0) ;
REM  ALTER TABLE "V500"."CODE_VALUE_SET" MODIFY ("DEFINITION_DUP_IND" 
REM  DEFAULT 0) ;
REM  ... 4252 rows
CREATE INDEX "V500"."XIE2CODE_VALUE_SET" ON "CODE_VALUE_SET" ("UPDT_DT_TM" 
) PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 196608 NEXT 1048576 
MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE 
"USERS" LOGGING ;
CREATE INDEX "V500"."XIE1CODE_VALUE_SET" ON "CODE_VALUE_SET" 
("CODE_SET_HITS" , "CODE_SET" ) PCTFREE 10 INITRANS 2 MAXTRANS 255 
STORAGE(INITIAL 196608 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST 
GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" LOGGING ;
CREATE UNIQUE INDEX "V500"."XPKCODE_VALUE_SET" ON "CODE_VALUE_SET" 
("CODE_SET" ) PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 196608 
NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL 
DEFAULT) TABLESPACE "USERS" LOGGING ;
CREATE INDEX "V500"."XIE3CODE_VALUE_SET" ON "CODE_VALUE_SET" 
("DISPLAY_KEY" ) PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 262144 
NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL 
DEFAULT) TABLESPACE "USERS" LOGGING ;
CREATE INDEX "V500"."XCERCODE_VALUE_SET0636" ON "CODE_VALUE_SET" 
("LAST_UTC_TS" ) PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 131072 
NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL 
DEFAULT) TABLESPACE "USERS" LOGGING ;
REM  ALTER TABLE "V500"."CODE_VALUE_SET" ADD CONSTRAINT 
REM  "XPKCODE_VALUE_SET" PRIMARY KEY ("CODE_SET") USING INDEX PCTFREE 10 
REM  INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 196608 NEXT 1048576 
REM  MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) 
REM  TABLESPACE "USERS" LOGGING ENABLE ;
REM  ALTER TABLE "V500"."CODE_VALUE_SET" ADD SUPPLEMENTAL LOG GROUP 
REM  "GGS_112058" ("CODE_SET") ALWAYS ;
REM  CREATE TABLE "V500"."CONCEPT_IDENTIFIER_DTA" ("TASK_ASSAY_CD" NUMBER, 
REM  "CONCEPT_CKI" VARCHAR2(25)) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
REM  255 STORAGE(INITIAL 720896 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 
REM  FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" LOGGING 
REM  NOCOMPRESS ;
REM  ... 22760 rows
CREATE INDEX "V500"."CID_IDX_01" ON "CONCEPT_IDENTIFIER_DTA" 
("TASK_ASSAY_CD" ) PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 
720896 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL 
DEFAULT) TABLESPACE "USERS" LOGGING ;
REM  CREATE TABLE "V500"."COUNT_EVENTS_MAY_2019" ("EVENT_CD" NUMBER, 
REM  "COUNT_DISTINCT_EVENT_ID" NUMBER) PCTFREE 10 PCTUSED 40 INITRANS 1 
REM  MAXTRANS 255 STORAGE(INITIAL 327680 NEXT 1048576 MINEXTENTS 1 
REM  FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" 
REM  LOGGING NOCOMPRESS ;
REM  ... 16260 rows
CREATE INDEX "V500"."ASFD" ON "COUNT_EVENTS_MAY_2019" ("EVENT_CD" ) 
PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 393216 NEXT 1048576 
MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE 
"USERS" LOGGING ;
REM  CREATE TABLE "V500"."DISCRETE_TASK_ASSAY" ("TASK_ASSAY_CD" NUMBER NOT 
REM  NULL ENABLE, "STRT_ASSAY_ID" NUMBER NOT NULL ENABLE, 
REM  "MNEMONIC_KEY_CAP" VARCHAR2(100), "ACTIVITY_TYPE_CD" NUMBER NOT NULL 
REM  ENABLE, "DEFAULT_RESULT_TYPE_CD" NUMBER NOT NULL ENABLE, "EVENT_CD" 
REM  NUMBER NOT NULL ENABLE, "TASK_REPT_IND" NUMBER, "MNEMONIC" 
REM  VARCHAR2(100), "DESCRIPTION" VARCHAR2(100), "TRANSMIT_INDICATOR" 
REM  NUMBER, "PRINT_RESULTS" NUMBER, "PRINT_REF_RANGES_ON_REPT" NUMBER, 
REM  "HISTORY_ACTIVITY_TYPE_CD" NUMBER NOT NULL ENABLE, 
REM  "SIGNATURE_LINE_IND" NUMBER NOT NULL ENABLE, "RENDERING_PROVIDER_IND" 
REM  NUMBER, "ICD_CODE_IND" NUMBER, "CERNER_DEFINED_IND" NUMBER, 
REM  "ACTIVE_IND" NUMBER, "UPDT_DT_TM" DATE NOT NULL ENABLE, "UPDT_ID" 
REM  NUMBER NOT NULL ENABLE, "UPDT_TASK" NUMBER NOT NULL ENABLE, 
REM  "UPDT_CNT" NUMBER NOT NULL ENABLE, "UPDT_APPLCTX" NUMBER NOT NULL 
REM  ENABLE, "HLA_LOCI_CD" NUMBER NOT NULL ENABLE, 
REM  "BB_RESULT_PROCESSING_CD" NUMBER NOT NULL ENABLE, "REF_RANGE_SCRIPT" 
REM  VARCHAR2(50), "CODE_SET" NUMBER, "ACTIVE_STATUS_CD" NUMBER NOT NULL 
REM  ENABLE, "ACTIVE_STATUS_DT_TM" DATE, "ACTIVE_STATUS_PRSNL_ID" NUMBER 
REM  NOT NULL ENABLE, "BEG_EFFECTIVE_DT_TM" DATE NOT NULL ENABLE, 
REM  "END_EFFECTIVE_DT_TM" DATE NOT NULL ENABLE, "INTERP_DATA_IND" NUMBER, 
REM  "RAD_SECTION_TYPE_CD" NUMBER NOT NULL ENABLE, "REL_ASSAY_IND" NUMBER, 
REM  "DELTA_LVL_FLAG" NUMBER, "MODIFIER_IND" NUMBER, "VERSION_NUMBER" 
REM  FLOAT(126) NOT NULL ENABLE, "SINGLE_SELECT_IND" NUMBER NOT NULL 
REM  ENABLE, "DEFAULT_TYPE_FLAG" NUMBER NOT NULL ENABLE, "CONCEPT_CKI" 
REM  VARCHAR2(255) NOT NULL ENABLE, "IO_FLAG" NUMBER NOT NULL DISABLE, 
REM  "SCI_NOTATION_IND" NUMBER NOT NULL DISABLE, "LABEL_TEMPLATE_ID" 
REM  NUMBER NOT NULL DISABLE, "TEMPLATE_SCRIPT_CD" NUMBER NOT NULL 
REM  DISABLE, "MNEMONIC_KEY_CAP_NLS" VARCHAR2(102) NOT NULL ENABLE, 
REM  "MNEMONIC_KEY_CAP_A_NLS" VARCHAR2(200), "LAST_UTC_TS" TIMESTAMP (9)) 
REM  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 
REM  10485760 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 
REM  BUFFER_POOL DEFAULT) TABLESPACE "USERS" LOGGING NOCOMPRESS ;
REM  ALTER TABLE "V500"."DISCRETE_TASK_ASSAY" MODIFY ("TASK_ASSAY_CD" 
REM  DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."DISCRETE_TASK_ASSAY" MODIFY ("STRT_ASSAY_ID" 
REM  DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."DISCRETE_TASK_ASSAY" MODIFY ("ACTIVITY_TYPE_CD" 
REM  DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."DISCRETE_TASK_ASSAY" MODIFY 
REM  ("DEFAULT_RESULT_TYPE_CD" DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."DISCRETE_TASK_ASSAY" MODIFY ("EVENT_CD" DEFAULT 0 
REM  ) ;
REM  ALTER TABLE "V500"."DISCRETE_TASK_ASSAY" MODIFY 
REM  ("HISTORY_ACTIVITY_TYPE_CD" DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."DISCRETE_TASK_ASSAY" MODIFY ("SIGNATURE_LINE_IND" 
REM  DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."DISCRETE_TASK_ASSAY" MODIFY ("UPDT_DT_TM" DEFAULT 
REM  SYSDATE ) ;
REM  ALTER TABLE "V500"."DISCRETE_TASK_ASSAY" MODIFY ("UPDT_ID" DEFAULT 0 
REM  ) ;
REM  ALTER TABLE "V500"."DISCRETE_TASK_ASSAY" MODIFY ("UPDT_TASK" DEFAULT 
REM  0 ) ;
REM  ALTER TABLE "V500"."DISCRETE_TASK_ASSAY" MODIFY ("UPDT_CNT" DEFAULT 0 
REM  ) ;
REM  ALTER TABLE "V500"."DISCRETE_TASK_ASSAY" MODIFY ("UPDT_APPLCTX" 
REM  DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."DISCRETE_TASK_ASSAY" MODIFY ("HLA_LOCI_CD" 
REM  DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."DISCRETE_TASK_ASSAY" MODIFY 
REM  ("BB_RESULT_PROCESSING_CD" DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."DISCRETE_TASK_ASSAY" MODIFY ("ACTIVE_STATUS_CD" 
REM  DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."DISCRETE_TASK_ASSAY" MODIFY 
REM  ("ACTIVE_STATUS_PRSNL_ID" DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."DISCRETE_TASK_ASSAY" MODIFY 
REM  ("BEG_EFFECTIVE_DT_TM" DEFAULT SYSDATE ) ;
REM  ALTER TABLE "V500"."DISCRETE_TASK_ASSAY" MODIFY 
REM  ("END_EFFECTIVE_DT_TM" DEFAULT TO_DATE( '12/31/2100 00:00:00' , 
REM  'MM/DD/YYYY HH24:MI:SS' ) ) ;
REM  ALTER TABLE "V500"."DISCRETE_TASK_ASSAY" MODIFY 
REM  ("RAD_SECTION_TYPE_CD" DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."DISCRETE_TASK_ASSAY" MODIFY ("MODIFIER_IND" 
REM  DEFAULT 0) ;
REM  ALTER TABLE "V500"."DISCRETE_TASK_ASSAY" MODIFY ("VERSION_NUMBER" 
REM  DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."DISCRETE_TASK_ASSAY" MODIFY ("SINGLE_SELECT_IND" 
REM  DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."DISCRETE_TASK_ASSAY" MODIFY ("DEFAULT_TYPE_FLAG" 
REM  DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."DISCRETE_TASK_ASSAY" MODIFY ("CONCEPT_CKI" 
REM  DEFAULT ' ' ) ;
REM  ALTER TABLE "V500"."DISCRETE_TASK_ASSAY" MODIFY ("IO_FLAG" DEFAULT 0 
REM  ) ;
REM  ALTER TABLE "V500"."DISCRETE_TASK_ASSAY" MODIFY ("SCI_NOTATION_IND" 
REM  DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."DISCRETE_TASK_ASSAY" MODIFY ("LABEL_TEMPLATE_ID" 
REM  DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."DISCRETE_TASK_ASSAY" MODIFY ("TEMPLATE_SCRIPT_CD" 
REM  DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."DISCRETE_TASK_ASSAY" MODIFY 
REM  ("MNEMONIC_KEY_CAP_NLS" DEFAULT ' ' ) ;
REM  ... 39351 rows
CREATE INDEX "V500"."XIE1DISCRETE_TASK_ASSAY" ON "DISCRETE_TASK_ASSAY" 
("MNEMONIC" , "ACTIVITY_TYPE_CD" ) PCTFREE 10 INITRANS 2 MAXTRANS 255 
STORAGE(INITIAL 3145728 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST 
GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" LOGGING ;
CREATE INDEX "V500"."XIE4DISCRETE_TASK_ASSAY" ON "DISCRETE_TASK_ASSAY" 
("ACTIVITY_TYPE_CD" , "DEFAULT_RESULT_TYPE_CD" ) PCTFREE 10 INITRANS 2 
MAXTRANS 255 STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 
FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" LOGGING ;
CREATE INDEX "V500"."XIE5DISCRETE_TASK_ASSAY" ON "DISCRETE_TASK_ASSAY" 
("EVENT_CD" ) PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 2097152 
NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL 
DEFAULT) TABLESPACE "USERS" LOGGING ;
CREATE INDEX "V500"."XIE6DISCRETE_TASK_ASSAY" ON "DISCRETE_TASK_ASSAY" 
("CONCEPT_CKI" ) PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 
2097152 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 
BUFFER_POOL DEFAULT) TABLESPACE "USERS" LOGGING ;
CREATE INDEX "V500"."XIE7DISCRETE_TASK_ASSAY" ON "DISCRETE_TASK_ASSAY" 
("HLA_LOCI_CD" ) PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 917504 
NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL 
DEFAULT) TABLESPACE "USERS" LOGGING ;
CREATE INDEX "V500"."XIE8DISCRETE_TASK_ASSAY" ON "DISCRETE_TASK_ASSAY" 
("MNEMONIC_KEY_CAP" ) PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 
3145728 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 
BUFFER_POOL DEFAULT) TABLESPACE "USERS" LOGGING ;
CREATE INDEX "V500"."XIE2DISCRETE_TASK_ASSAY" ON "DISCRETE_TASK_ASSAY" 
("BB_RESULT_PROCESSING_CD" ) PCTFREE 10 INITRANS 2 MAXTRANS 255 
STORAGE(INITIAL 917504 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST 
GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" LOGGING ;
CREATE UNIQUE INDEX "V500"."XPKDISCRETE_TASK_ASSAY" ON 
"DISCRETE_TASK_ASSAY" ("TASK_ASSAY_CD" ) PCTFREE 10 INITRANS 2 MAXTRANS 
255 STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST 
GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" LOGGING ;
CREATE INDEX "V500"."XIE3DISCRETE_TASK_ASSAY" ON "DISCRETE_TASK_ASSAY" 
("STRT_ASSAY_ID" ) PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 
917504 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL 
DEFAULT) TABLESPACE "USERS" LOGGING ;
CREATE INDEX "V500"."XCERDISCRETE_TASK_1291" ON "DISCRETE_TASK_ASSAY" 
("LAST_UTC_TS" ) PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 458752 
NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL 
DEFAULT) TABLESPACE "USERS" LOGGING ;
REM  ALTER TABLE "V500"."DISCRETE_TASK_ASSAY" ADD CONSTRAINT 
REM  "XPKDISCRETE_TASK_ASSAY" PRIMARY KEY ("TASK_ASSAY_CD") USING INDEX 
REM  PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 2097152 NEXT 
REM  1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL 
REM  DEFAULT) TABLESPACE "USERS" LOGGING ENABLE ;
REM  ALTER TABLE "V500"."DISCRETE_TASK_ASSAY" ADD SUPPLEMENTAL LOG GROUP 
REM  "GGS_112287" ("TASK_ASSAY_CD") ALWAYS ;
REM  CREATE TABLE "V500"."GL_ORDRS_NO_PP_COMP_201903_ODS" ("SYNONYM_ID" 
REM  NUMBER, "ORDER_MNEMONIC" VARCHAR2(255), "COUNT_ORDERS" NUMBER) 
REM  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 131072 
REM  NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL 
REM  DEFAULT) TABLESPACE "USERS" LOGGING NOCOMPRESS ;
REM  ... 1568 rows
REM  CREATE TABLE "V500"."HIER" ("HIERARCHY_NODE_TYPE" VARCHAR2(23), 
REM  "EVENT_SET_CD" NUMBER, "PARENT_EVENT_SET_CD" NUMBER, 
REM  "EVENT_SET_COLLATING_SEQ" NUMBER, "EVENT_SET_CD_DISP" VARCHAR2(131), 
REM  "ACTIVE_IND" VARCHAR2(40)) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
REM  255 STORAGE(INITIAL 16777216 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 
REM  FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" LOGGING 
REM  NOCOMPRESS ;
REM  ... 213785 rows
CREATE INDEX "V500"."HIER1" ON "HIER" ("EVENT_SET_CD" ) PCTFREE 10 
INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 5242880 NEXT 1048576 MINEXTENTS 1 
FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" 
LOGGING ;
CREATE INDEX "V500"."HIER2" ON "HIER" ("PARENT_EVENT_SET_CD" ) PCTFREE 10 
INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 5242880 NEXT 1048576 MINEXTENTS 1 
FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" 
LOGGING ;
REM  CREATE TABLE "V500"."OCS_FACILITY_R" ("SYNONYM_ID" NUMBER NOT NULL 
REM  ENABLE, "FACILITY_CD" NUMBER NOT NULL ENABLE, "UPDT_ID" NUMBER NOT 
REM  NULL ENABLE, "UPDT_DT_TM" DATE NOT NULL ENABLE, "UPDT_TASK" NUMBER 
REM  NOT NULL ENABLE, "UPDT_APPLCTX" NUMBER NOT NULL ENABLE, "UPDT_CNT" 
REM  NUMBER NOT NULL ENABLE, "LAST_UTC_TS" TIMESTAMP (9)) PCTFREE 10 
REM  PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 13631488 NEXT 
REM  1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL 
REM  DEFAULT) TABLESPACE "USERS" LOGGING NOCOMPRESS ;
REM  ALTER TABLE "V500"."OCS_FACILITY_R" MODIFY ("SYNONYM_ID" DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."OCS_FACILITY_R" MODIFY ("FACILITY_CD" DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."OCS_FACILITY_R" MODIFY ("UPDT_ID" DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."OCS_FACILITY_R" MODIFY ("UPDT_DT_TM" DEFAULT 
REM  SYSDATE ) ;
REM  ALTER TABLE "V500"."OCS_FACILITY_R" MODIFY ("UPDT_TASK" DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."OCS_FACILITY_R" MODIFY ("UPDT_APPLCTX" DEFAULT 0 
REM  ) ;
REM  ALTER TABLE "V500"."OCS_FACILITY_R" MODIFY ("UPDT_CNT" DEFAULT 0 ) ;
REM  ... 236833 rows
CREATE UNIQUE INDEX "V500"."TEMP_OCS_FACILITY_R_PK" ON "OCS_FACILITY_R" 
("SYNONYM_ID" , "FACILITY_CD" ) PCTFREE 10 INITRANS 2 MAXTRANS 255 
STORAGE(INITIAL 9437184 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST 
GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" LOGGING ;
REM  ALTER TABLE "V500"."OCS_FACILITY_R" ADD SUPPLEMENTAL LOG GROUP 
REM  "GGS_114650" ("SYNONYM_ID", "FACILITY_CD") ALWAYS ;
REM  ALTER TABLE "V500"."OCS_FACILITY_R" ADD CONSTRAINT 
REM  "TEMP_OCS_FACILITY_R_PK" PRIMARY KEY ("SYNONYM_ID", "FACILITY_CD") 
REM  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 
REM  9437184 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 
REM  BUFFER_POOL DEFAULT) TABLESPACE "USERS" LOGGING ENABLE ;
REM  CREATE TABLE "V500"."ORDER_CATALOG" ("CATALOG_CD" NUMBER NOT NULL 
REM  ENABLE, "REVIEW_HIERARCHY_ID" NUMBER NOT NULL ENABLE, 
REM  "ABN_REVIEW_IND" NUMBER, "RESOURCE_ROUTE_CD" NUMBER NOT NULL ENABLE, 
REM  "ACTIVITY_TYPE_CD" NUMBER NOT NULL ENABLE, "RESOURCE_ROUTE_LVL" 
REM  NUMBER, "CONSENT_FORM_IND" NUMBER, "ACTIVE_IND" NUMBER, "PROMPT_IND" 
REM  NUMBER, "CATALOG_TYPE_CD" NUMBER NOT NULL ENABLE, 
REM  "REQUISITION_FORMAT_CD" NUMBER NOT NULL ENABLE, 
REM  "REQUISITION_ROUTING_CD" NUMBER NOT NULL ENABLE, 
REM  "INST_RESTRICTION_IND" NUMBER, "SCHEDULE_IND" NUMBER, "DESCRIPTION" 
REM  VARCHAR2(100), "PRINT_REQ_IND" NUMBER, "OE_FORMAT_ID" NUMBER NOT NULL 
REM  ENABLE, "ORDERABLE_TYPE_FLAG" NUMBER, "QUICK_CHART_IND" NUMBER, 
REM  "COMPLETE_UPON_ORDER_IND" NUMBER, "COMMENT_TEMPLATE_FLAG" NUMBER, 
REM  "PREP_INFO_FLAG" NUMBER, "UPDT_DT_TM" DATE NOT NULL ENABLE, "UPDT_ID" 
REM  NUMBER NOT NULL ENABLE, "UPDT_TASK" NUMBER NOT NULL ENABLE, 
REM  "UPDT_CNT" NUMBER NOT NULL ENABLE, "UPDT_APPLCTX" NUMBER NOT NULL 
REM  ENABLE, "EVENT_CD" NUMBER NOT NULL ENABLE, "ACTIVITY_SUBTYPE_CD" 
REM  NUMBER NOT NULL ENABLE, "DUP_CHECKING_IND" NUMBER, "BILL_ONLY_IND" 
REM  NUMBER, "CONT_ORDER_METHOD_FLAG" NUMBER, "DEPT_DUP_CHECK_IND" NUMBER, 
REM  "PRIMARY_MNEMONIC" VARCHAR2(100) NOT NULL ENABLE, "ORDER_REVIEW_IND" 
REM  NUMBER, "CONSENT_FORM_FORMAT_CD" NUMBER NOT NULL ENABLE, 
REM  "CONSENT_FORM_ROUTING_CD" NUMBER NOT NULL ENABLE, "DEPT_DISPLAY_NAME" 
REM  VARCHAR2(100), "REF_TEXT_MASK" NUMBER, "CS_INDEX_CD" NUMBER NOT NULL 
REM  ENABLE, "SOURCE_VOCAB_MEAN" VARCHAR2(12), "SOURCE_VOCAB_IDENT" 
REM  VARCHAR2(50), "ORD_COM_TEMPLATE_LONG_TEXT_ID" NUMBER NOT NULL ENABLE, 
REM  "MODIFIABLE_FLAG" NUMBER, "DCP_CLIN_CAT_CD" NUMBER NOT NULL ENABLE, 
REM  "AUTO_CANCEL_IND" NUMBER, "CKI" VARCHAR2(255), "STOP_TYPE_CD" NUMBER 
REM  NOT NULL ENABLE, "STOP_DURATION" NUMBER, "STOP_DURATION_UNIT_CD" 
REM  NUMBER NOT NULL ENABLE, "DC_DISPLAY_DAYS" NUMBER, 
REM  "DC_INTERACTION_DAYS" NUMBER, "DISABLE_ORDER_COMMENT_IND" NUMBER, 
REM  "FORM_ID" NUMBER NOT NULL ENABLE, "FORM_LEVEL" NUMBER, "CONCEPT_CKI" 
REM  VARCHAR2(255), "IC_AUTO_VERIFY_FLAG" NUMBER NOT NULL ENABLE, 
REM  "DISCERN_AUTO_VERIFY_FLAG" NUMBER NOT NULL ENABLE, 
REM  "VETTING_APPROVAL_FLAG" NUMBER NOT NULL DISABLE, "OP_DC_DISPLAY_DAYS" 
REM  NUMBER NOT NULL DISABLE, "OP_DC_INTERACTION_DAYS" NUMBER NOT NULL 
REM  DISABLE, "DOSING_ALL_INGRED_IND" NUMBER NOT NULL DISABLE, 
REM  "DOSING_ACT_INGRED_CODE" NUMBER, "LAST_UTC_TS" TIMESTAMP (9)) PCTFREE 
REM  10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 14680064 NEXT 
REM  1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL 
REM  DEFAULT) TABLESPACE "USERS" LOGGING NOCOMPRESS ;
REM  ALTER TABLE "V500"."ORDER_CATALOG" MODIFY ("CATALOG_CD" DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG" MODIFY ("REVIEW_HIERARCHY_ID" 
REM  DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG" MODIFY ("RESOURCE_ROUTE_CD" 
REM  DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG" MODIFY ("ACTIVITY_TYPE_CD" DEFAULT 
REM  0 ) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG" MODIFY ("CATALOG_TYPE_CD" DEFAULT 
REM  0 ) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG" MODIFY ("REQUISITION_FORMAT_CD" 
REM  DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG" MODIFY ("REQUISITION_ROUTING_CD" 
REM  DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG" MODIFY ("OE_FORMAT_ID" DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG" MODIFY ("UPDT_DT_TM" DEFAULT 
REM  SYSDATE ) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG" MODIFY ("UPDT_ID" DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG" MODIFY ("UPDT_TASK" DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG" MODIFY ("UPDT_CNT" DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG" MODIFY ("UPDT_APPLCTX" DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG" MODIFY ("EVENT_CD" DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG" MODIFY ("ACTIVITY_SUBTYPE_CD" 
REM  DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG" MODIFY ("PRIMARY_MNEMONIC" DEFAULT 
REM  ' ' ) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG" MODIFY ("CONSENT_FORM_FORMAT_CD" 
REM  DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG" MODIFY ("CONSENT_FORM_ROUTING_CD" 
REM  DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG" MODIFY ("CS_INDEX_CD" DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG" MODIFY 
REM  ("ORD_COM_TEMPLATE_LONG_TEXT_ID" DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG" MODIFY ("MODIFIABLE_FLAG" DEFAULT 
REM  0) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG" MODIFY ("DCP_CLIN_CAT_CD" DEFAULT 
REM  0 ) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG" MODIFY ("AUTO_CANCEL_IND" DEFAULT 
REM  0) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG" MODIFY ("STOP_TYPE_CD" DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG" MODIFY ("STOP_DURATION" DEFAULT 0) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG" MODIFY ("STOP_DURATION_UNIT_CD" 
REM  DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG" MODIFY ("DC_DISPLAY_DAYS" DEFAULT 
REM  0) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG" MODIFY ("DC_INTERACTION_DAYS" 
REM  DEFAULT 0) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG" MODIFY 
REM  ("DISABLE_ORDER_COMMENT_IND" DEFAULT 0) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG" MODIFY ("FORM_ID" DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG" MODIFY ("CONCEPT_CKI" DEFAULT 
REM  NULL) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG" MODIFY ("IC_AUTO_VERIFY_FLAG" 
REM  DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG" MODIFY ("DISCERN_AUTO_VERIFY_FLAG" 
REM  DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG" MODIFY ("VETTING_APPROVAL_FLAG" 
REM  DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG" MODIFY ("OP_DC_DISPLAY_DAYS" 
REM  DEFAULT -1 ) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG" MODIFY ("OP_DC_INTERACTION_DAYS" 
REM  DEFAULT -1 ) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG" MODIFY ("DOSING_ALL_INGRED_IND" 
REM  DEFAULT 0 ) ;
REM  ... 42508 rows
CREATE INDEX "V500"."XIE4ORDER_CATALOG" ON "ORDER_CATALOG" ("UPDT_DT_TM" ) 
PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 2097152 NEXT 1048576 
MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE 
"USERS" LOGGING ;
CREATE INDEX "V500"."XIE1ORDER_CATALOG" ON "ORDER_CATALOG" ("CKI" ) 
PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 851968 NEXT 1048576 
MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE 
"USERS" LOGGING ;
CREATE UNIQUE INDEX "V500"."XAK1ORDER_CATALOG" ON "ORDER_CATALOG" 
("PRIMARY_MNEMONIC" ) PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 
4194304 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 
BUFFER_POOL DEFAULT) TABLESPACE "USERS" LOGGING ;
CREATE INDEX "V500"."XIE_ORDER_CATALOG" ON "ORDER_CATALOG" 
("CATALOG_TYPE_CD" , "ACTIVITY_TYPE_CD" ) PCTFREE 10 INITRANS 2 MAXTRANS 
255 STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST 
GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" LOGGING ;
CREATE UNIQUE INDEX "V500"."XPKORDER_CATALOG" ON "ORDER_CATALOG" 
("CATALOG_CD" ) PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 2097152 
NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL 
DEFAULT) TABLESPACE "USERS" LOGGING ;
CREATE INDEX "V500"."XIE3ORDER_CATALOG" ON "ORDER_CATALOG" ("CONCEPT_CKI" 
) PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 524288 NEXT 1048576 
MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE 
"USERS" LOGGING ;
CREATE INDEX "V500"."XCERORDER_CATALOG0151" ON "ORDER_CATALOG" 
("LAST_UTC_TS" ) PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 
2097152 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 
BUFFER_POOL DEFAULT) TABLESPACE "USERS" LOGGING ;
REM  ALTER TABLE "V500"."ORDER_CATALOG" ADD CONSTRAINT "XPKORDER_CATALOG" 
REM  PRIMARY KEY ("CATALOG_CD") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 
REM  255 STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 
REM  FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" LOGGING 
REM  ENABLE ;
REM  ALTER TABLE "V500"."ORDER_CATALOG" ADD SUPPLEMENTAL LOG GROUP 
REM  "GGS_113143" ("CATALOG_CD") ALWAYS ;
REM  CREATE TABLE "V500"."ORDER_CATALOG_SYNONYM" ("SYNONYM_ID" NUMBER NOT 
REM  NULL ENABLE, "CATALOG_CD" NUMBER NOT NULL ENABLE, "CATALOG_TYPE_CD" 
REM  NUMBER NOT NULL ENABLE, "MNEMONIC" VARCHAR2(100), "MNEMONIC_KEY_CAP" 
REM  VARCHAR2(100), "MNEMONIC_TYPE_CD" NUMBER NOT NULL ENABLE, 
REM  "OE_FORMAT_ID" NUMBER NOT NULL ENABLE, "ORDER_SENTENCE_ID" NUMBER NOT 
REM  NULL ENABLE, "ACTIVE_IND" NUMBER, "ACTIVITY_TYPE_CD" NUMBER NOT NULL 
REM  ENABLE, "UPDT_APPLCTX" NUMBER NOT NULL ENABLE, "UPDT_CNT" NUMBER NOT 
REM  NULL ENABLE, "UPDT_DT_TM" DATE NOT NULL ENABLE, "UPDT_ID" NUMBER NOT 
REM  NULL ENABLE, "UPDT_TASK" NUMBER NOT NULL ENABLE, 
REM  "ACTIVITY_SUBTYPE_CD" NUMBER NOT NULL ENABLE, "ORDERABLE_TYPE_FLAG" 
REM  NUMBER, "ACTIVE_STATUS_CD" NUMBER NOT NULL ENABLE, 
REM  "ACTIVE_STATUS_DT_TM" DATE, "ACTIVE_STATUS_PRSNL_ID" NUMBER NOT NULL 
REM  ENABLE, "REF_TEXT_MASK" NUMBER, "CS_INDEX_CD" NUMBER NOT NULL ENABLE, 
REM  "MULTIPLE_ORD_SENT_IND" NUMBER, "HIDE_FLAG" NUMBER, "RX_MASK" NUMBER, 
REM  "DCP_CLIN_CAT_CD" NUMBER NOT NULL ENABLE, "FILTERED_OD_IND" NUMBER, 
REM  "ITEM_ID" NUMBER NOT NULL ENABLE, "CKI" VARCHAR2(255), 
REM  "MNEMONIC_KEY_CAP_NLS" VARCHAR2(405), "VIRTUAL_VIEW" VARCHAR2(100), 
REM  "HEALTH_PLAN_VIEW" VARCHAR2(255), "CONCEPT_CKI" VARCHAR2(255), 
REM  "CONCENTRATION_STRENGTH" FLOAT(126), "CONCENTRATION_STRENGTH_UNIT_CD" 
REM  NUMBER NOT NULL ENABLE, "CONCENTRATION_VOLUME" FLOAT(126), 
REM  "CONCENTRATION_VOLUME_UNIT_CD" NUMBER NOT NULL ENABLE, 
REM  "TEMPLATE_MNEMONIC_FLAG" NUMBER NOT NULL ENABLE, 
REM  "INGREDIENT_RATE_CONVERSION_IND" NUMBER NOT NULL ENABLE, 
REM  "WITNESS_FLAG" NUMBER NOT NULL ENABLE, "HIGH_ALERT_LONG_TEXT_ID" 
REM  NUMBER NOT NULL DISABLE, "HIGH_ALERT_IND" NUMBER NOT NULL DISABLE, 
REM  "HIGH_ALERT_REQUIRED_NTFY_IND" NUMBER, "ROUNDING_RULE_CD" NUMBER, 
REM  "MED_INTERVAL_WARN_FLAG" NUMBER NOT NULL DISABLE, 
REM  "LAST_ADMIN_DISP_BASIS_FLAG" NUMBER NOT NULL DISABLE, 
REM  "DISPLAY_ADDITIVES_FIRST_IND" NUMBER NOT NULL DISABLE, 
REM  "MNEMONIC_KEY_CAP_A_NLS" VARCHAR2(400), "INTERMITTENT_IND" NUMBER NOT 
REM  NULL DISABLE, "IGNORE_HIDE_CONVERT_IND" NUMBER NOT NULL DISABLE, 
REM  "LOCK_TARGET_DOSE_IND" NUMBER NOT NULL DISABLE, "AUTOPROG_SYN_IND" 
REM  NUMBER NOT NULL DISABLE, "MAX_FINAL_DOSE" FLOAT(126) NOT NULL 
REM  DISABLE, "PREFERRED_DOSE_FLAG" NUMBER NOT NULL DISABLE, 
REM  "MAX_DOSE_CALC_BSA_VALUE" NUMBER NOT NULL DISABLE, 
REM  "MAX_FINAL_DOSE_UNIT_CD" NUMBER NOT NULL DISABLE, "LAST_UTC_TS" 
REM  TIMESTAMP (9)) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
REM  STORAGE(INITIAL 35651584 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 
REM  FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" LOGGING 
REM  NOCOMPRESS ;
REM  ALTER TABLE "V500"."ORDER_CATALOG_SYNONYM" MODIFY ("SYNONYM_ID" 
REM  DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG_SYNONYM" MODIFY ("CATALOG_CD" 
REM  DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG_SYNONYM" MODIFY ("CATALOG_TYPE_CD" 
REM  DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG_SYNONYM" MODIFY ("MNEMONIC_TYPE_CD" 
REM  DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG_SYNONYM" MODIFY ("OE_FORMAT_ID" 
REM  DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG_SYNONYM" MODIFY 
REM  ("ORDER_SENTENCE_ID" DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG_SYNONYM" MODIFY ("ACTIVITY_TYPE_CD" 
REM  DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG_SYNONYM" MODIFY ("UPDT_APPLCTX" 
REM  DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG_SYNONYM" MODIFY ("UPDT_CNT" DEFAULT 
REM  0 ) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG_SYNONYM" MODIFY ("UPDT_DT_TM" 
REM  DEFAULT SYSDATE ) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG_SYNONYM" MODIFY ("UPDT_ID" DEFAULT 
REM  0 ) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG_SYNONYM" MODIFY ("UPDT_TASK" 
REM  DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG_SYNONYM" MODIFY 
REM  ("ACTIVITY_SUBTYPE_CD" DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG_SYNONYM" MODIFY ("ACTIVE_STATUS_CD" 
REM  DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG_SYNONYM" MODIFY 
REM  ("ACTIVE_STATUS_PRSNL_ID" DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG_SYNONYM" MODIFY ("CS_INDEX_CD" 
REM  DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG_SYNONYM" MODIFY ("RX_MASK" DEFAULT 
REM  0) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG_SYNONYM" MODIFY ("DCP_CLIN_CAT_CD" 
REM  DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG_SYNONYM" MODIFY ("ITEM_ID" DEFAULT 
REM  0 ) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG_SYNONYM" MODIFY ("CONCEPT_CKI" 
REM  DEFAULT NULL) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG_SYNONYM" MODIFY 
REM  ("CONCENTRATION_STRENGTH" DEFAULT NULL) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG_SYNONYM" MODIFY 
REM  ("CONCENTRATION_STRENGTH_UNIT_CD" DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG_SYNONYM" MODIFY 
REM  ("CONCENTRATION_VOLUME" DEFAULT NULL) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG_SYNONYM" MODIFY 
REM  ("CONCENTRATION_VOLUME_UNIT_CD" DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG_SYNONYM" MODIFY 
REM  ("TEMPLATE_MNEMONIC_FLAG" DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG_SYNONYM" MODIFY 
REM  ("INGREDIENT_RATE_CONVERSION_IND" DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG_SYNONYM" MODIFY ("WITNESS_FLAG" 
REM  DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG_SYNONYM" MODIFY 
REM  ("HIGH_ALERT_LONG_TEXT_ID" DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG_SYNONYM" MODIFY ("HIGH_ALERT_IND" 
REM  DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG_SYNONYM" MODIFY 
REM  ("HIGH_ALERT_REQUIRED_NTFY_IND" DEFAULT 0) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG_SYNONYM" MODIFY 
REM  ("MED_INTERVAL_WARN_FLAG" DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG_SYNONYM" MODIFY 
REM  ("LAST_ADMIN_DISP_BASIS_FLAG" DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG_SYNONYM" MODIFY 
REM  ("DISPLAY_ADDITIVES_FIRST_IND" DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG_SYNONYM" MODIFY ("INTERMITTENT_IND" 
REM  DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG_SYNONYM" MODIFY 
REM  ("IGNORE_HIDE_CONVERT_IND" DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG_SYNONYM" MODIFY 
REM  ("LOCK_TARGET_DOSE_IND" DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG_SYNONYM" MODIFY ("AUTOPROG_SYN_IND" 
REM  DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG_SYNONYM" MODIFY ("MAX_FINAL_DOSE" 
REM  DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG_SYNONYM" MODIFY 
REM  ("PREFERRED_DOSE_FLAG" DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG_SYNONYM" MODIFY 
REM  ("MAX_DOSE_CALC_BSA_VALUE" DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."ORDER_CATALOG_SYNONYM" MODIFY 
REM  ("MAX_FINAL_DOSE_UNIT_CD" DEFAULT 0 ) ;
REM  ... 109284 rows
CREATE INDEX "V500"."XIE10ORDER_CATALOG_SYNONYM" ON 
"ORDER_CATALOG_SYNONYM" ("UPDT_DT_TM" ) PCTFREE 10 INITRANS 2 MAXTRANS 255 
STORAGE(INITIAL 4194304 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST 
GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" LOGGING ;
CREATE INDEX "V500"."XIE90ORDER_CATALOG_SYNONYM" ON 
"ORDER_CATALOG_SYNONYM" ("CONCEPT_CKI" ) PCTFREE 10 INITRANS 2 MAXTRANS 
255 STORAGE(INITIAL 3145728 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST 
GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" LOGGING ;
CREATE INDEX "V500"."XIE5ORDER_CATALOG_SYNONYM" ON "ORDER_CATALOG_SYNONYM" 
("MNEMONIC_KEY_CAP" , "SYNONYM_ID" ) PCTFREE 10 INITRANS 2 MAXTRANS 255 
STORAGE(INITIAL 9437184 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST 
GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" LOGGING ;
CREATE INDEX "V500"."XIF411ORDER_CATALOG_SYNONYM" ON 
"ORDER_CATALOG_SYNONYM" ("ORDER_SENTENCE_ID" ) PCTFREE 10 INITRANS 2 
MAXTRANS 255 STORAGE(INITIAL 3145728 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 
FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" LOGGING ;
CREATE INDEX "V500"."XIE6ORDER_CATALOG_SYNONYM" ON "ORDER_CATALOG_SYNONYM" 
("MNEMONIC_KEY_CAP" , "MNEMONIC_TYPE_CD" , "CATALOG_TYPE_CD" , 
"ORDERABLE_TYPE_FLAG" ) PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 
9437184 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 
BUFFER_POOL DEFAULT) TABLESPACE "USERS" LOGGING ;
CREATE INDEX "V500"."XIE8ORDER_CATALOG_SYNONYM" ON "ORDER_CATALOG_SYNONYM" 
("CKI" , "MNEMONIC_TYPE_CD" ) PCTFREE 10 INITRANS 2 MAXTRANS 255 
STORAGE(INITIAL 5242880 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST 
GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" LOGGING ;
CREATE UNIQUE INDEX "V500"."XAK1ORDER_CATALOG_SYNONYM" ON 
"ORDER_CATALOG_SYNONYM" ("CATALOG_CD" , "MNEMONIC_TYPE_CD" , 
"MNEMONIC_KEY_CAP" , "ITEM_ID" ) PCTFREE 10 INITRANS 2 MAXTRANS 255 
STORAGE(INITIAL 9437184 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST 
GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" LOGGING ;
CREATE INDEX "V500"."XIE3ORDER_CATALOG_SYNONYM" ON "ORDER_CATALOG_SYNONYM" 
("CATALOG_TYPE_CD" , "MNEMONIC_KEY_CAP" ) PCTFREE 10 INITRANS 2 MAXTRANS 
255 STORAGE(INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST 
GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" LOGGING ;
CREATE INDEX "V500"."XIE4ORDER_CATALOG_SYNONYM" ON "ORDER_CATALOG_SYNONYM" 
("ACTIVITY_TYPE_CD" , "MNEMONIC_KEY_CAP" ) PCTFREE 10 INITRANS 2 MAXTRANS 
255 STORAGE(INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST 
GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" LOGGING ;
CREATE UNIQUE INDEX "V500"."XPKORDER_CATALOG_SYNONYM" ON 
"ORDER_CATALOG_SYNONYM" ("SYNONYM_ID" ) PCTFREE 10 INITRANS 2 MAXTRANS 255 
STORAGE(INITIAL 3145728 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST 
GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" LOGGING ;
CREATE INDEX "V500"."XCERORDER_CATALOG_1390" ON "ORDER_CATALOG_SYNONYM" 
("LAST_UTC_TS" ) PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 
3145728 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 
BUFFER_POOL DEFAULT) TABLESPACE "USERS" LOGGING ;
REM  ALTER TABLE "V500"."ORDER_CATALOG_SYNONYM" ADD CONSTRAINT 
REM  "XPKORDER_CATALOG_SYNONYM" PRIMARY KEY ("SYNONYM_ID") USING INDEX 
REM  PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 3145728 NEXT 
REM  1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL 
REM  DEFAULT) TABLESPACE "USERS" LOGGING ENABLE ;
REM  ALTER TABLE "V500"."ORDER_CATALOG_SYNONYM" ADD SUPPLEMENTAL LOG GROUP 
REM  "GGS_113146" ("SYNONYM_ID") ALWAYS ;
REM  CREATE TABLE "V500"."ORDER_SENTENCES_BEDROCK" ("ORDERABLE_DISP" 
REM  VARCHAR2(255), "SYNONYM_DISP" VARCHAR2(255), "MNEMONIC_KEY_CAP" 
REM  VARCHAR2(255), "SYNONYM_TYPE" VARCHAR2(255), "SYNONYM_ID" NUMBER, 
REM  "ORDER_ENTRY_FORMAT" VARCHAR2(255), "ORDER_SENTENCE_ID" NUMBER, 
REM  "ORDER_SENTENCE" VARCHAR2(255)) PCTFREE 10 PCTUSED 40 INITRANS 1 
REM  MAXTRANS 255 STORAGE(INITIAL 917504 NEXT 1048576 MINEXTENTS 1 
REM  FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" 
REM  LOGGING NOCOMPRESS ;
REM  ... 5116 rows
REM  CREATE TABLE "V500"."PET" ("PET_ID" NUMBER NOT NULL ENABLE, 
REM  "PET_NAME" VARCHAR2(20) NOT NULL ENABLE, "PET_TYPE" VARCHAR2(20) NOT 
REM  NULL ENABLE, "OWNER_ID" NUMBER NOT NULL ENABLE) PCTFREE 10 PCTUSED 40 
REM  INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 
REM  1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE 
REM  "USERS" LOGGING NOCOMPRESS ;
REM  ... 4 rows
CREATE UNIQUE INDEX "V500"."PET_PK" ON "PET" ("PET_ID" ) PCTFREE 10 
INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 
FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" 
LOGGING ;
REM  ALTER TABLE "V500"."PET" ADD CONSTRAINT "PET_PK" PRIMARY KEY 
REM  ("PET_ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
REM  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST 
REM  GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" LOGGING ENABLE ;
REM  CREATE TABLE "V500"."PET_OWNER" ("OWNER_ID" NUMBER NOT NULL ENABLE, 
REM  "LAST_NAME" VARCHAR2(20) NOT NULL ENABLE, "FIRST_NAME" VARCHAR2(20)) 
REM  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 65536 
REM  NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL 
REM  DEFAULT) TABLESPACE "USERS" LOGGING NOCOMPRESS ;
REM  ... 3 rows
CREATE UNIQUE INDEX "V500"."PET_OWNER_PK" ON "PET_OWNER" ("OWNER_ID" ) 
PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 
MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE 
"USERS" LOGGING ;
REM  ALTER TABLE "V500"."PET_OWNER" ADD CONSTRAINT "PET_OWNER_PK" PRIMARY 
REM  KEY ("OWNER_ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
REM  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST 
REM  GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" LOGGING ENABLE ;
REM  CREATE TABLE "V500"."PROFILE_TASK_R" ("CATALOG_CD" NUMBER NOT NULL 
REM  ENABLE, "TASK_ASSAY_CD" NUMBER NOT NULL ENABLE, "VERSION_NBR" NUMBER, 
REM  "GROUP_CD" NUMBER NOT NULL ENABLE, "ITEM_TYPE_FLAG" NUMBER, 
REM  "PENDING_IND" NUMBER, "REPEAT_IND" NUMBER, "SEQUENCE" NUMBER, 
REM  "DUP_CHK_MIN" NUMBER, "DUP_CHK_ACTION_CD" NUMBER NOT NULL ENABLE, 
REM  "UPDT_DT_TM" DATE NOT NULL ENABLE, "UPDT_ID" NUMBER NOT NULL ENABLE, 
REM  "UPDT_TASK" NUMBER NOT NULL ENABLE, "UPDT_CNT" NUMBER NOT NULL 
REM  ENABLE, "UPDT_APPLCTX" NUMBER NOT NULL ENABLE, "ACTIVE_IND" NUMBER, 
REM  "POST_PROMPT_IND" NUMBER, "PROMPT_RESOURCE_CD" NUMBER NOT NULL 
REM  ENABLE, "ACTIVE_STATUS_CD" NUMBER NOT NULL ENABLE, 
REM  "ACTIVE_STATUS_DT_TM" DATE, "ACTIVE_STATUS_PRSNL_ID" NUMBER NOT NULL 
REM  ENABLE, "BEG_EFFECTIVE_DT_TM" DATE NOT NULL ENABLE, 
REM  "END_EFFECTIVE_DT_TM" DATE NOT NULL ENABLE, "REFERENCE_TASK_ID" 
REM  NUMBER NOT NULL ENABLE, "PROMPT_LONG_TEXT_ID" NUMBER NOT NULL ENABLE, 
REM  "RESTRICT_DISPLAY_IND" NUMBER, "LAST_UTC_TS" TIMESTAMP (9)) PCTFREE 
REM  10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 3145728 NEXT 
REM  1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL 
REM  DEFAULT) TABLESPACE "USERS" LOGGING NOCOMPRESS ;
REM  ALTER TABLE "V500"."PROFILE_TASK_R" MODIFY ("CATALOG_CD" DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."PROFILE_TASK_R" MODIFY ("TASK_ASSAY_CD" DEFAULT 0 
REM  ) ;
REM  ALTER TABLE "V500"."PROFILE_TASK_R" MODIFY ("GROUP_CD" DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."PROFILE_TASK_R" MODIFY ("DUP_CHK_ACTION_CD" 
REM  DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."PROFILE_TASK_R" MODIFY ("UPDT_DT_TM" DEFAULT 
REM  SYSDATE ) ;
REM  ALTER TABLE "V500"."PROFILE_TASK_R" MODIFY ("UPDT_ID" DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."PROFILE_TASK_R" MODIFY ("UPDT_TASK" DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."PROFILE_TASK_R" MODIFY ("UPDT_CNT" DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."PROFILE_TASK_R" MODIFY ("UPDT_APPLCTX" DEFAULT 0 
REM  ) ;
REM  ALTER TABLE "V500"."PROFILE_TASK_R" MODIFY ("PROMPT_RESOURCE_CD" 
REM  DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."PROFILE_TASK_R" MODIFY ("ACTIVE_STATUS_CD" 
REM  DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."PROFILE_TASK_R" MODIFY ("ACTIVE_STATUS_PRSNL_ID" 
REM  DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."PROFILE_TASK_R" MODIFY ("BEG_EFFECTIVE_DT_TM" 
REM  DEFAULT SYSDATE ) ;
REM  ALTER TABLE "V500"."PROFILE_TASK_R" MODIFY ("END_EFFECTIVE_DT_TM" 
REM  DEFAULT TO_DATE('12/31/2100 00:00:00','MM/DD/YYYY HH24:MI:SS') ) ;
REM  ALTER TABLE "V500"."PROFILE_TASK_R" MODIFY ("REFERENCE_TASK_ID" 
REM  DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."PROFILE_TASK_R" MODIFY ("PROMPT_LONG_TEXT_ID" 
REM  DEFAULT 0 ) ;
REM  ... 20179 rows
CREATE INDEX "V500"."XIF76PROFILE_TASK_R" ON "PROFILE_TASK_R" 
("VERSION_NBR" , "GROUP_CD" ) PCTFREE 10 INITRANS 2 MAXTRANS 255 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST 
GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" LOGGING ;
CREATE UNIQUE INDEX "V500"."XPKPROFILE_TASK_R" ON "PROFILE_TASK_R" 
("CATALOG_CD" , "TASK_ASSAY_CD" ) PCTFREE 10 INITRANS 2 MAXTRANS 255 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST 
GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" LOGGING ;
CREATE INDEX "V500"."XIF346PROFILE_TASK_R" ON "PROFILE_TASK_R" 
("TASK_ASSAY_CD" ) PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 
65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL 
DEFAULT) TABLESPACE "USERS" LOGGING ;
CREATE INDEX "V500"."XIF431PROFILE_TASK_R" ON "PROFILE_TASK_R" ("GROUP_CD" 
, "VERSION_NBR" ) PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 65536 
NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL 
DEFAULT) TABLESPACE "USERS" LOGGING ;
CREATE INDEX "V500"."XCERPROFILE_TASK_R1381" ON "PROFILE_TASK_R" 
("LAST_UTC_TS" ) PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 65536 
NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL 
DEFAULT) TABLESPACE "USERS" LOGGING ;
REM  ALTER TABLE "V500"."PROFILE_TASK_R" ADD CONSTRAINT 
REM  "XPKPROFILE_TASK_R" PRIMARY KEY ("CATALOG_CD", "TASK_ASSAY_CD") USING 
REM  INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 
REM  1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL 
REM  DEFAULT) TABLESPACE "USERS" LOGGING ENABLE ;
REM  ALTER TABLE "V500"."PROFILE_TASK_R" ADD SUPPLEMENTAL LOG GROUP 
REM  "GGS_113516" ("CATALOG_CD", "TASK_ASSAY_CD") ALWAYS ;
REM  CREATE TABLE "V500"."TEMP_SYNONYM_FACILITY" ("SYNONYM_ID" NUMBER, 
REM  "FACILITY_CD" NUMBER) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
REM  STORAGE(INITIAL 5242880 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 
REM  FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" LOGGING 
REM  NOCOMPRESS ;
REM  ... 236714 rows
CREATE UNIQUE INDEX "V500"."TEMP_SYN_FAC_PK" ON "TEMP_SYNONYM_FACILITY" 
("SYNONYM_ID" , "FACILITY_CD" ) PCTFREE 10 INITRANS 2 MAXTRANS 255 
STORAGE(INITIAL 9437184 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST 
GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" LOGGING ;
REM  ALTER TABLE "V500"."TEMP_SYNONYM_FACILITY" ADD CONSTRAINT 
REM  "TEMP_SYN_FAC_PK" PRIMARY KEY ("SYNONYM_ID", "FACILITY_CD") USING 
REM  INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 9437184 NEXT 
REM  1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL 
REM  DEFAULT) TABLESPACE "USERS" LOGGING ENABLE ;
REM  CREATE TABLE "V500"."V500_EVENT_CODE" ("EVENT_CD" NUMBER NOT NULL 
REM  ENABLE, "EVENT_CD_DEFINITION" VARCHAR2(100), "EVENT_CD_DESCR" 
REM  VARCHAR2(60), "EVENT_CD_DISP" VARCHAR2(100), "EVENT_CD_DISP_KEY" 
REM  VARCHAR2(40), "CODE_STATUS_CD" NUMBER NOT NULL ENABLE, 
REM  "DEF_DOCMNT_ATTRIBUTES" VARCHAR2(255), "DEF_DOCMNT_FORMAT_CD" NUMBER 
REM  NOT NULL ENABLE, "DEF_DOCMNT_STORAGE_CD" NUMBER NOT NULL ENABLE, 
REM  "DEF_EVENT_CLASS_CD" NUMBER NOT NULL ENABLE, 
REM  "DEF_EVENT_CONFID_LEVEL_CD" NUMBER NOT NULL ENABLE, "DEF_EVENT_LEVEL" 
REM  NUMBER, "EVENT_ADD_ACCESS_IND" NUMBER, "EVENT_CD_SUBCLASS_CD" NUMBER 
REM  NOT NULL ENABLE, "EVENT_CHG_ACCESS_IND" NUMBER, "EVENT_SET_NAME" 
REM  VARCHAR2(100), "RETENTION_DAYS" NUMBER, "UPDT_APPLCTX" NUMBER NOT 
REM  NULL ENABLE, "UPDT_CNT" NUMBER NOT NULL ENABLE, "UPDT_DT_TM" DATE NOT 
REM  NULL ENABLE, "UPDT_ID" NUMBER NOT NULL ENABLE, "UPDT_TASK" NUMBER NOT 
REM  NULL ENABLE, "EVENT_CODE_STATUS_CD" NUMBER NOT NULL ENABLE, 
REM  "COLLATING_SEQ" NUMBER NOT NULL ENABLE, "LAST_UTC_TS" TIMESTAMP (9)) 
REM  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 262144 
REM  NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL 
REM  DEFAULT) TABLESPACE "USERS" LOGGING NOCOMPRESS ;
REM  ALTER TABLE "V500"."V500_EVENT_CODE" MODIFY ("EVENT_CD" DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."V500_EVENT_CODE" MODIFY ("CODE_STATUS_CD" DEFAULT 
REM  0 ) ;
REM  ALTER TABLE "V500"."V500_EVENT_CODE" MODIFY ("DEF_DOCMNT_FORMAT_CD" 
REM  DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."V500_EVENT_CODE" MODIFY ("DEF_DOCMNT_STORAGE_CD" 
REM  DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."V500_EVENT_CODE" MODIFY ("DEF_EVENT_CLASS_CD" 
REM  DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."V500_EVENT_CODE" MODIFY 
REM  ("DEF_EVENT_CONFID_LEVEL_CD" DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."V500_EVENT_CODE" MODIFY ("EVENT_CD_SUBCLASS_CD" 
REM  DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."V500_EVENT_CODE" MODIFY ("UPDT_APPLCTX" DEFAULT 0 
REM  ) ;
REM  ALTER TABLE "V500"."V500_EVENT_CODE" MODIFY ("UPDT_CNT" DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."V500_EVENT_CODE" MODIFY ("UPDT_DT_TM" DEFAULT 
REM  SYSDATE ) ;
REM  ALTER TABLE "V500"."V500_EVENT_CODE" MODIFY ("UPDT_ID" DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."V500_EVENT_CODE" MODIFY ("UPDT_TASK" DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."V500_EVENT_CODE" MODIFY ("EVENT_CODE_STATUS_CD" 
REM  DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."V500_EVENT_CODE" MODIFY ("COLLATING_SEQ" DEFAULT 
REM  0 ) ;
REM  ... 46455 rows
CREATE INDEX "V500"."XIE1V500_EVENT_CODE" ON "V500_EVENT_CODE" 
("EVENT_CD_DISP_KEY" ) PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 
131072 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL 
DEFAULT) TABLESPACE "USERS" LOGGING ;
CREATE INDEX "V500"."XIE2V500_EVENT_CODE" ON "V500_EVENT_CODE" 
("EVENT_ADD_ACCESS_IND" , "EVENT_CD_DISP_KEY" , "EVENT_CD_SUBCLASS_CD" ) 
PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 131072 NEXT 1048576 
MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE 
"USERS" LOGGING ;
CREATE INDEX "V500"."XIE3V500_EVENT_CODE" ON "V500_EVENT_CODE" 
("EVENT_CHG_ACCESS_IND" , "EVENT_CD_DISP_KEY" , "EVENT_CD_SUBCLASS_CD" ) 
PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 131072 NEXT 1048576 
MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE 
"USERS" LOGGING ;
CREATE UNIQUE INDEX "V500"."XPKV500_EVENT_CODE" ON "V500_EVENT_CODE" 
("EVENT_CD" ) PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 65536 
NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL 
DEFAULT) TABLESPACE "USERS" LOGGING ;
CREATE INDEX "V500"."XCERV500_EVENT_COD0349" ON "V500_EVENT_CODE" 
("LAST_UTC_TS" ) PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 65536 
NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL 
DEFAULT) TABLESPACE "USERS" LOGGING ;
REM  ALTER TABLE "V500"."V500_EVENT_CODE" ADD CONSTRAINT 
REM  "XPKV500_EVENT_CODE" PRIMARY KEY ("EVENT_CD") USING INDEX PCTFREE 10 
REM  INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 
REM  1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE 
REM  "USERS" LOGGING ENABLE ;
REM  ALTER TABLE "V500"."V500_EVENT_CODE" ADD SUPPLEMENTAL LOG GROUP 
REM  "GGS_114079" ("EVENT_CD") ALWAYS ;
REM  CREATE TABLE "V500"."V500_EVENT_SET_CANON" ("PARENT_EVENT_SET_CD" 
REM  NUMBER NOT NULL ENABLE, "EVENT_SET_CD" NUMBER NOT NULL ENABLE, 
REM  "EVENT_SET_COLLATING_SEQ" NUMBER, "EVENT_SET_EXPLODE_IND" NUMBER, 
REM  "EVENT_SET_STATUS_CD" NUMBER NOT NULL ENABLE, "UPDT_DT_TM" DATE NOT 
REM  NULL ENABLE, "UPDT_TASK" NUMBER NOT NULL ENABLE, "UPDT_ID" NUMBER NOT 
REM  NULL ENABLE, "UPDT_CNT" NUMBER NOT NULL ENABLE, "UPDT_APPLCTX" NUMBER 
REM  NOT NULL ENABLE, "LAST_UTC_TS" TIMESTAMP (9), "DM2_MIG_SEQ_ID" 
REM  NUMBER) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 
REM  65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 
REM  BUFFER_POOL DEFAULT) TABLESPACE "USERS" LOGGING NOCOMPRESS ;
REM  ALTER TABLE "V500"."V500_EVENT_SET_CANON" MODIFY 
REM  ("PARENT_EVENT_SET_CD" DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."V500_EVENT_SET_CANON" MODIFY ("EVENT_SET_CD" 
REM  DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."V500_EVENT_SET_CANON" MODIFY 
REM  ("EVENT_SET_STATUS_CD" DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."V500_EVENT_SET_CANON" MODIFY ("UPDT_DT_TM" 
REM  DEFAULT SYSDATE ) ;
REM  ALTER TABLE "V500"."V500_EVENT_SET_CANON" MODIFY ("UPDT_TASK" DEFAULT 
REM  0 ) ;
REM  ALTER TABLE "V500"."V500_EVENT_SET_CANON" MODIFY ("UPDT_ID" DEFAULT 0 
REM  ) ;
REM  ALTER TABLE "V500"."V500_EVENT_SET_CANON" MODIFY ("UPDT_CNT" DEFAULT 
REM  0 ) ;
REM  ALTER TABLE "V500"."V500_EVENT_SET_CANON" MODIFY ("UPDT_APPLCTX" 
REM  DEFAULT 0 ) ;
REM  ... 71353 rows
CREATE INDEX "V500"."XIE1V500_EVENT_SET_CANON" ON "V500_EVENT_SET_CANON" 
("PARENT_EVENT_SET_CD" ) PCTFREE 10 INITRANS 2 MAXTRANS 255 
STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST 
GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" LOGGING ;
CREATE INDEX "V500"."XIE2V500_EVENT_SET_CANON" ON "V500_EVENT_SET_CANON" 
("EVENT_SET_CD" , "PARENT_EVENT_SET_CD" ) PCTFREE 10 INITRANS 2 MAXTRANS 
255 STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST 
GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" LOGGING ;
CREATE INDEX "V500"."XCERV500_EVENT_SET0350" ON "V500_EVENT_SET_CANON" 
("LAST_UTC_TS" ) PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 65536 
NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL 
DEFAULT) TABLESPACE "USERS" LOGGING ;
REM  ALTER TABLE "V500"."V500_EVENT_SET_CANON" ADD SUPPLEMENTAL LOG GROUP 
REM  "GGS_114080" ("DM2_MIG_SEQ_ID") ALWAYS ;
REM  CREATE TABLE "V500"."V500_EVENT_SET_CODE" ("ACCUMULATION_IND" NUMBER, 
REM  "CATEGORY_FLAG" NUMBER, "EVENT_SET_CD_DEFINITION" VARCHAR2(100), 
REM  "EVENT_SET_CD_DESCR" VARCHAR2(60), "EVENT_SET_CD_DISP" VARCHAR2(40), 
REM  "EVENT_SET_CD_DISP_KEY" VARCHAR2(40), "CODE_STATUS_CD" NUMBER NOT 
REM  NULL ENABLE, "EVENT_SET_CD" NUMBER NOT NULL ENABLE, "COMBINE_FORMAT" 
REM  VARCHAR2(200), "EVENT_SET_COLOR_NAME" VARCHAR2(16), 
REM  "EVENT_SET_ICON_NAME" VARCHAR2(16), "EVENT_SET_NAME" VARCHAR2(40) NOT 
REM  NULL ENABLE, "EVENT_SET_NAME_KEY" VARCHAR2(40), "EVENT_SET_STATUS_CD" 
REM  NUMBER NOT NULL ENABLE, "GROUPING_RULE_FLAG" NUMBER, 
REM  "LEAF_EVENT_CD_COUNT" NUMBER, "OPERATION_DISPLAY_FLAG" NUMBER, 
REM  "OPERATION_FORMULA" VARCHAR2(200), "PRIMITIVE_EVENT_SET_COUNT" 
REM  NUMBER, "SHOW_IF_NO_DATA_IND" NUMBER, "UPDT_APPLCTX" NUMBER NOT NULL 
REM  ENABLE, "UPDT_CNT" NUMBER NOT NULL ENABLE, "UPDT_DT_TM" DATE NOT NULL 
REM  ENABLE, "UPDT_ID" NUMBER NOT NULL ENABLE, "UPDT_TASK" NUMBER NOT NULL 
REM  ENABLE, "DISPLAY_ASSOCIATION_IND" NUMBER NOT NULL ENABLE, 
REM  "LAST_UTC_TS" TIMESTAMP (9)) PCTFREE 10 PCTUSED 40 INITRANS 1 
REM  MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 
REM  FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" 
REM  LOGGING NOCOMPRESS ;
REM  ALTER TABLE "V500"."V500_EVENT_SET_CODE" MODIFY ("CODE_STATUS_CD" 
REM  DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."V500_EVENT_SET_CODE" MODIFY ("EVENT_SET_CD" 
REM  DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."V500_EVENT_SET_CODE" MODIFY ("EVENT_SET_NAME" 
REM  DEFAULT ' ' ) ;
REM  ALTER TABLE "V500"."V500_EVENT_SET_CODE" MODIFY 
REM  ("EVENT_SET_STATUS_CD" DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."V500_EVENT_SET_CODE" MODIFY ("UPDT_APPLCTX" 
REM  DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."V500_EVENT_SET_CODE" MODIFY ("UPDT_CNT" DEFAULT 0 
REM  ) ;
REM  ALTER TABLE "V500"."V500_EVENT_SET_CODE" MODIFY ("UPDT_DT_TM" DEFAULT 
REM  SYSDATE ) ;
REM  ALTER TABLE "V500"."V500_EVENT_SET_CODE" MODIFY ("UPDT_ID" DEFAULT 0 
REM  ) ;
REM  ALTER TABLE "V500"."V500_EVENT_SET_CODE" MODIFY ("UPDT_TASK" DEFAULT 
REM  0 ) ;
REM  ALTER TABLE "V500"."V500_EVENT_SET_CODE" MODIFY 
REM  ("DISPLAY_ASSOCIATION_IND" DEFAULT 0 ) ;
REM  ... 26667 rows
CREATE INDEX "V500"."XIE1V500_EVENT_SET_CODE" ON "V500_EVENT_SET_CODE" 
("EVENT_SET_NAME_KEY" ) PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 
65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL 
DEFAULT) TABLESPACE "USERS" LOGGING ;
CREATE UNIQUE INDEX "V500"."XIE2V500_EVENT_SET_CODE" ON 
"V500_EVENT_SET_CODE" ("EVENT_SET_NAME" ) PCTFREE 10 INITRANS 2 MAXTRANS 
255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST 
GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" LOGGING ;
CREATE UNIQUE INDEX "V500"."XPKV500_EVENT_SET_CODE" ON 
"V500_EVENT_SET_CODE" ("EVENT_SET_CD" ) PCTFREE 10 INITRANS 2 MAXTRANS 255 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST 
GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" LOGGING ;
CREATE INDEX "V500"."XCERV500_EVENT_SET5356" ON "V500_EVENT_SET_CODE" 
("LAST_UTC_TS" ) PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 65536 
NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL 
DEFAULT) TABLESPACE "USERS" LOGGING ;
REM  ALTER TABLE "V500"."V500_EVENT_SET_CODE" ADD CONSTRAINT 
REM  "XPKV500_EVENT_SET_CODE" PRIMARY KEY ("EVENT_SET_CD") USING INDEX 
REM  PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 
REM  MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) 
REM  TABLESPACE "USERS" LOGGING ENABLE ;
REM  ALTER TABLE "V500"."V500_EVENT_SET_CODE" ADD SUPPLEMENTAL LOG GROUP 
REM  "GGS_114081" ("EVENT_SET_CD") ALWAYS ;
REM  CREATE TABLE "V500"."V500_EVENT_SET_EXPLODE" ("EVENT_CD" NUMBER NOT 
REM  NULL ENABLE, "EVENT_SET_CD" NUMBER NOT NULL ENABLE, 
REM  "EVENT_SET_STATUS_CD" NUMBER NOT NULL ENABLE, "UPDT_DT_TM" DATE NOT 
REM  NULL ENABLE, "UPDT_TASK" NUMBER NOT NULL ENABLE, "UPDT_ID" NUMBER NOT 
REM  NULL ENABLE, "UPDT_CNT" NUMBER NOT NULL ENABLE, "UPDT_APPLCTX" NUMBER 
REM  NOT NULL ENABLE, "EVENT_SET_LEVEL" NUMBER, "LAST_UTC_TS" TIMESTAMP 
REM  (9), "DM2_MIG_SEQ_ID" NUMBER) PCTFREE 10 PCTUSED 40 INITRANS 1 
REM  MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 
REM  FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" 
REM  LOGGING NOCOMPRESS ;
REM  ALTER TABLE "V500"."V500_EVENT_SET_EXPLODE" MODIFY ("EVENT_CD" 
REM  DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."V500_EVENT_SET_EXPLODE" MODIFY ("EVENT_SET_CD" 
REM  DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."V500_EVENT_SET_EXPLODE" MODIFY 
REM  ("EVENT_SET_STATUS_CD" DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."V500_EVENT_SET_EXPLODE" MODIFY ("UPDT_DT_TM" 
REM  DEFAULT SYSDATE ) ;
REM  ALTER TABLE "V500"."V500_EVENT_SET_EXPLODE" MODIFY ("UPDT_TASK" 
REM  DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."V500_EVENT_SET_EXPLODE" MODIFY ("UPDT_ID" DEFAULT 
REM  0 ) ;
REM  ALTER TABLE "V500"."V500_EVENT_SET_EXPLODE" MODIFY ("UPDT_CNT" 
REM  DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."V500_EVENT_SET_EXPLODE" MODIFY ("UPDT_APPLCTX" 
REM  DEFAULT 0 ) ;
REM  ALTER TABLE "V500"."V500_EVENT_SET_EXPLODE" MODIFY ("EVENT_SET_LEVEL" 
REM  DEFAULT NULL) ;
REM  ... 379149 rows
CREATE INDEX "V500"."XIE2V500_EVENT_SET_EXPLODE" ON 
"V500_EVENT_SET_EXPLODE" ("EVENT_SET_CD" , "EVENT_CD" ) PCTFREE 10 
INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 
FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" 
LOGGING ;
CREATE INDEX "V500"."XIF50V500_EVENT_SET_EXPLODE" ON 
"V500_EVENT_SET_EXPLODE" ("EVENT_CD" ) PCTFREE 10 INITRANS 2 MAXTRANS 255 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST 
GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" LOGGING ;
CREATE INDEX "V500"."XCERV500_EVENT_SET0351" ON "V500_EVENT_SET_EXPLODE" 
("LAST_UTC_TS" ) PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 65536 
NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL 
DEFAULT) TABLESPACE "USERS" LOGGING ;
REM  ALTER TABLE "V500"."V500_EVENT_SET_EXPLODE" ADD SUPPLEMENTAL LOG 
REM  GROUP "GGS_114082" ("DM2_MIG_SEQ_ID") ALWAYS ;
REM  ALTER TABLE "V500"."V500_EVENT_SET_EXPLODE" ADD CONSTRAINT 
REM  "XFK1V500_EVENT_SET_EXPLODE" FOREIGN KEY ("EVENT_CD") REFERENCES 
REM  "V500_EVENT_CODE" ("EVENT_CD") DISABLE NOVALIDATE ;
REM  ALTER TABLE "V500"."DISCRETE_TASK_ASSAY" ADD CONSTRAINT 
REM  "XFK1DISCRETE_TASK_ASSAY" FOREIGN KEY ("TASK_ASSAY_CD") REFERENCES 
REM  "CODE_VALUE" ("CODE_VALUE") DISABLE NOVALIDATE ;
REM  ALTER TABLE "V500"."ORDER_CATALOG" ADD CONSTRAINT "XFK3ORDER_CATALOG" 
REM  FOREIGN KEY ("CATALOG_CD") REFERENCES "CODE_VALUE" ("CODE_VALUE") 
REM  DISABLE NOVALIDATE ;
REM  ALTER TABLE "V500"."CODE_VALUE_ALIAS" ADD CONSTRAINT 
REM  "XFK2CODE_VALUE_ALIAS" FOREIGN KEY ("CODE_VALUE") REFERENCES 
REM  "CODE_VALUE" ("CODE_VALUE") DISABLE NOVALIDATE ;
REM  ALTER TABLE "V500"."CODE_VALUE_ALIAS" ADD CONSTRAINT 
REM  "XFK1CODE_VALUE_ALIAS" FOREIGN KEY ("CODE_SET") REFERENCES 
REM  "CODE_VALUE_SET" ("CODE_SET") DISABLE NOVALIDATE ;
REM  ALTER TABLE "V500"."PROFILE_TASK_R" ADD CONSTRAINT 
REM  "XFK2PROFILE_TASK_R" FOREIGN KEY ("TASK_ASSAY_CD") REFERENCES 
REM  "DISCRETE_TASK_ASSAY" ("TASK_ASSAY_CD") DISABLE NOVALIDATE ;
REM  ALTER TABLE "V500"."ORDER_CATALOG_SYNONYM" ADD CONSTRAINT 
REM  "XFK1ORDER_CATALOG_SYNONYM" FOREIGN KEY ("CATALOG_CD") REFERENCES 
REM  "ORDER_CATALOG" ("CATALOG_CD") DISABLE NOVALIDATE ;
REM  ALTER TABLE "V500"."OCS_FACILITY_R" ADD CONSTRAINT 
REM  "XFK1OCS_FACILITY_R" FOREIGN KEY ("SYNONYM_ID") REFERENCES 
REM  "ORDER_CATALOG_SYNONYM" ("SYNONYM_ID") DISABLE NOVALIDATE ;
REM  ALTER TABLE "V500"."PET" ADD CONSTRAINT "PET_PET_OWNER_FK" FOREIGN 
REM  KEY ("OWNER_ID") REFERENCES "PET_OWNER" ("OWNER_ID") ENABLE 
REM  NOVALIDATE ;
REM  ALTER TABLE "V500"."PET" ENABLE CONSTRAINT "PET_PET_OWNER_FK" ;
